<?php
namespace Database\Seeders;
use App\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [[
            'id'=>4,
            'alpha2'=>'AF',
            'alpha3'=>'AFG',
            'langCS'=>'Afghanistán',
            'lang_de'=>'Afghanistan',
            'lang_en'=>'Afghanistan',
            'langES'=>'Afganistán',
            'langFR'=>'Afghanistan',
            'langIT'=>'Afghanistan',
            'langNL'=>'Afghanistan',
        ],
            [
                'id'=>8,
                'alpha2'=>'AL',
                'alpha3'=>'ALB',
                'langCS'=>'Albánie',
                'lang_de'=>'Albanien',
                'lang_en'=>'Albania',
                'langES'=>'Albania',
                'langFR'=>'Albanie',
                'langIT'=>'Albania',
                'langNL'=>'Albanië',
            ],
            [
                'id'=>10,
                'alpha2'=>'AQ',
                'alpha3'=>'ATA',
                'langCS'=>'Antarctica',
                'lang_de'=>'Antarktis',
                'lang_en'=>'Antarctica',
                'langES'=>'Antartida',
                'langFR'=>'Antarctique',
                'langIT'=>'Antartide',
                'langNL'=>'Antarctica',
            ],
            [
                'id'=>12,
                'alpha2'=>'DZ',
                'alpha3'=>'DZA',
                'langCS'=>'Alžírsko',
                'lang_de'=>'Algerien',
                'lang_en'=>'Algeria',
                'langES'=>'Argelia',
                'langFR'=>'Algérie',
                'langIT'=>'Algeria',
                'langNL'=>'Algerije',
            ],
            [
                'id'=>16,
                'alpha2'=>'AS',
                'alpha3'=>'ASM',
                'langCS'=>'Americká Samoa',
                'lang_de'=>'Amerikanisch-Samoa',
                'lang_en'=>'American Samoa',
                'langES'=>'Samoa americana',
                'langFR'=>'Samoa Américaines',
                'langIT'=>'Samoa Americane',
                'langNL'=>'Amerikaans Samoa',
            ],
            [
                'id'=>20,
                'alpha2'=>'AD',
                'alpha3'=>'AND',
                'langCS'=>'Andorra',
                'lang_de'=>'Andorra',
                'lang_en'=>'Andorra',
                'langES'=>'Andorra',
                'langFR'=>'Andorre',
                'langIT'=>'Andorra',
                'langNL'=>'Andorra',
            ],
            [
                'id'=>24,
                'alpha2'=>'AO',
                'alpha3'=>'AGO',
                'langCS'=>'Angola',
                'lang_de'=>'Angola',
                'lang_en'=>'Angola',
                'langES'=>'Angola',
                'langFR'=>'Angola',
                'langIT'=>'Angola',
                'langNL'=>'Angola',
            ],
            [
                'id'=>28,
                'alpha2'=>'AG',
                'alpha3'=>'ATG',
                'langCS'=>'Antigua a Barbuda',
                'lang_de'=>'Antigua und Barbuda',
                'lang_en'=>'Antigua and Barbuda',
                'langES'=>'Antigua y Barbuda',
                'langFR'=>'Antigua-et-Barbuda',
                'langIT'=>'Antigua e Barbuda',
                'langNL'=>'Antigua en Barbuda',
            ],
            [
                'id'=>31,
                'alpha2'=>'AZ',
                'alpha3'=>'AZE',
                'langCS'=>'Azerbajdžán',
                'lang_de'=>'Aserbaidschan',
                'lang_en'=>'Azerbaijan',
                'langES'=>'Azerbaiyán',
                'langFR'=>'Azerbaïdjan',
                'langIT'=>'Azerbaijan',
                'langNL'=>'Azerbeidzjan',
            ],
            [
                'id'=>32,
                'alpha2'=>'AR',
                'alpha3'=>'ARG',
                'langCS'=>'Argentina',
                'lang_de'=>'Argentinien',
                'lang_en'=>'Argentina',
                'langES'=>'Argentina',
                'langFR'=>'Argentine',
                'langIT'=>'Argentina',
                'langNL'=>'Argentinië',
            ],
            [
                'id'=>36,
                'alpha2'=>'AU',
                'alpha3'=>'AUS',
                'langCS'=>'Austrálie',
                'lang_de'=>'Australien',
                'lang_en'=>'Australia',
                'langES'=>'Australia',
                'langFR'=>'Australie',
                'langIT'=>'Australia',
                'langNL'=>'Australië',
            ],
            [
                'id'=>40,
                'alpha2'=>'AT',
                'alpha3'=>'AUT',
                'langCS'=>'Rakousko',
                'lang_de'=>'Österreich',
                'lang_en'=>'Austria',
                'langES'=>'Austria',
                'langFR'=>'Autriche',
                'langIT'=>'Austria',
                'langNL'=>'Oostenrijk',
            ],
            [
                'id'=>44,
                'alpha2'=>'BS',
                'alpha3'=>'BHS',
                'langCS'=>'Bahamy',
                'lang_de'=>'Bahamas',
                'lang_en'=>'Bahamas',
                'langES'=>'Bahamas',
                'langFR'=>'Bahamas',
                'langIT'=>'Bahamas',
                'langNL'=>'Bahama',
            ],
            [
                'id'=>48,
                'alpha2'=>'BH',
                'alpha3'=>'BHR',
                'langCS'=>'Bahrajn',
                'lang_de'=>'Bahrain',
                'lang_en'=>'Bahrain',
                'langES'=>'Bahrain',
                'langFR'=>'Bahreïn',
                'langIT'=>'Bahrain',
                'langNL'=>'Bahrein',
            ],
            [
                'id'=>50,
                'alpha2'=>'BD',
                'alpha3'=>'BGD',
                'langCS'=>'Bangladéš',
                'lang_de'=>'Bangladesch',
                'lang_en'=>'Bangladesh',
                'langES'=>'Bangladesh',
                'langFR'=>'Bangladesh',
                'langIT'=>'Bangladesh',
                'langNL'=>'Bangladesh',
            ],
            [
                'id'=>51,
                'alpha2'=>'AM',
                'alpha3'=>'ARM',
                'langCS'=>'Arménie',
                'lang_de'=>'Armenien',
                'lang_en'=>'Armenia',
                'langES'=>'Armenia',
                'langFR'=>'Arménie',
                'langIT'=>'Armenia',
                'langNL'=>'Armenië',
            ],
            [
                'id'=>52,
                'alpha2'=>'BB',
                'alpha3'=>'BRB',
                'langCS'=>'Barbados',
                'lang_de'=>'Barbados',
                'lang_en'=>'Barbados',
                'langES'=>'Barbados',
                'langFR'=>'Barbade',
                'langIT'=>'Barbados',
                'langNL'=>'Barbados',
            ],
            [
                'id'=>56,
                'alpha2'=>'BE',
                'alpha3'=>'BEL',
                'langCS'=>'Belgie',
                'lang_de'=>'Belgien',
                'lang_en'=>'Belgium',
                'langES'=>'Bélgica',
                'langFR'=>'Belgique',
                'langIT'=>'Belgio',
                'langNL'=>'België',
            ],
            [
                'id'=>60,
                'alpha2'=>'BM',
                'alpha3'=>'BMU',
                'langCS'=>'Bermuda',
                'lang_de'=>'Bermuda',
                'lang_en'=>'Bermuda',
                'langES'=>'Bermuda',
                'langFR'=>'Bermudes',
                'langIT'=>'Bermuda',
                'langNL'=>'Bermuda',
            ],
            [
                'id'=>64,
                'alpha2'=>'BT',
                'alpha3'=>'BTN',
                'langCS'=>'Bhután',
                'lang_de'=>'Bhutan',
                'lang_en'=>'Bhutan',
                'langES'=>'Bhutan',
                'langFR'=>'Bhoutan',
                'langIT'=>'Bhutan',
                'langNL'=>'Bhutan',
            ],
            [
                'id'=>68,
                'alpha2'=>'BO',
                'alpha3'=>'BOL',
                'langCS'=>'Bolívie',
                'lang_de'=>'Bolivien',
                'lang_en'=>'Bolivia',
                'langES'=>'Bolivia',
                'langFR'=>'Bolivie',
                'langIT'=>'Bolivia',
                'langNL'=>'Bolivia',
            ],
            [
                'id'=>70,
                'alpha2'=>'BA',
                'alpha3'=>'BIH',
                'langCS'=>'Bosna a Hercegovina',
                'lang_de'=>'Bosnien und Herzegowina',
                'lang_en'=>'Bosnia and Herzegovina',
                'langES'=>'Bosnia y Herzegovina',
                'langFR'=>'Bosnie-Herzégovine',
                'langIT'=>'Bosnia Erzegovina',
                'langNL'=>'Bosnië-Herzegovina',
            ],
            [
                'id'=>72,
                'alpha2'=>'BW',
                'alpha3'=>'BWA',
                'langCS'=>'Botswana',
                'lang_de'=>'Botswana',
                'lang_en'=>'Botswana',
                'langES'=>'Botswana',
                'langFR'=>'Botswana',
                'langIT'=>'Botswana',
                'langNL'=>'Botswana',
            ],
            [
                'id'=>74,
                'alpha2'=>'BV',
                'alpha3'=>'BVT',
                'langCS'=>'Bouvet Island',
                'lang_de'=>'Bouvetinsel',
                'lang_en'=>'Bouvet Island',
                'langES'=>'Isla Bouvet',
                'langFR'=>'Île Bouvet',
                'langIT'=>'Isola di Bouvet',
                'langNL'=>'Bouvet',
            ],
            [
                'id'=>76,
                'alpha2'=>'BR',
                'alpha3'=>'BRA',
                'langCS'=>'Brazílie',
                'lang_de'=>'Brasilien',
                'lang_en'=>'Brazil',
                'langES'=>'Brasil',
                'langFR'=>'Brésil',
                'langIT'=>'Brasile',
                'langNL'=>'Brazilië',
            ],
            [
                'id'=>84,
                'alpha2'=>'BZ',
                'alpha3'=>'BLZ',
                'langCS'=>'Belize',
                'lang_de'=>'Belize',
                'lang_en'=>'Belize',
                'langES'=>'Belize',
                'langFR'=>'Belize',
                'langIT'=>'Belize',
                'langNL'=>'Belize',
            ],
            [
                'id'=>86,
                'alpha2'=>'IO',
                'alpha3'=>'IOT',
                'langCS'=>'Britské Indickooceánské teritorium',
                'lang_de'=>'Britisches Territorium im Indischen Ozean',
                'lang_en'=>'British Indian Ocean Territory',
                'langES'=>'Territorio Oceánico de la India Británica',
                'langFR'=>'Territoire Britannique de l',
                'langIT'=>'Océan Indien',
                'langNL'=>'Territori Britannici dell',
            ],
            [
                'id'=>90,
                'alpha2'=>'SB',
                'alpha3'=>'SLB',
                'langCS'=>'Šalamounovy ostrovy',
                'lang_de'=>'Salomonen',
                'lang_en'=>'Solomon Islands',
                'langES'=>'Islas Salomón',
                'langFR'=>'Îles Salomon',
                'langIT'=>'Isole Solomon',
                'langNL'=>'Salomonseilanden',
            ],
            [
                'id'=>92,
                'alpha2'=>'VG',
                'alpha3'=>'VGB',
                'langCS'=>'Britské Panenské ostrovy',
                'lang_de'=>'Britische Jungferninseln',
                'lang_en'=>'British Virgin Islands',
                'langES'=>'Islas Vírgenes Británicas',
                'langFR'=>'Îles Vierges Britanniques',
                'langIT'=>'Isole Vergini Britanniche',
                'langNL'=>'Britse Maagdeneilanden',
            ],
            [
                'id'=>96,
                'alpha2'=>'BN',
                'alpha3'=>'BRN',
                'langCS'=>'Brunej',
                'lang_de'=>'Brunei Darussalam',
                'lang_en'=>'Brunei Darussalam',
                'langES'=>'Brunei Darussalam',
                'langFR'=>'Brunéi Darussalam',
                'langIT'=>'Brunei Darussalam',
                'langNL'=>'Brunei',
            ],
            [
                'id'=>100,
                'alpha2'=>'BG',
                'alpha3'=>'BGR',
                'langCS'=>'Bulharsko',
                'lang_de'=>'Bulgarien',
                'lang_en'=>'Bulgaria',
                'langES'=>'Bulgaria',
                'langFR'=>'Bulgarie',
                'langIT'=>'Bulgaria',
                'langNL'=>'Bulgarije',
            ],
            [
                'id'=>104,
                'alpha2'=>'MM',
                'alpha3'=>'MMR',
                'langCS'=>'Myanmar',
                'lang_de'=>'Myanmar',
                'lang_en'=>'Myanmar',
                'langES'=>'Mianmar',
                'langFR'=>'Myanmar',
                'langIT'=>'Myanmar',
                'langNL'=>'Myanmar',
            ],
            [
                'id'=>108,
                'alpha2'=>'BI',
                'alpha3'=>'BDI',
                'langCS'=>'Burundi',
                'lang_de'=>'Burundi',
                'lang_en'=>'Burundi',
                'langES'=>'Burundi',
                'langFR'=>'Burundi',
                'langIT'=>'Burundi',
                'langNL'=>'Burundi',
            ],
            [
                'id'=>112,
                'alpha2'=>'BY',
                'alpha3'=>'BLR',
                'langCS'=>'Bělorusko',
                'lang_de'=>'Belarus',
                'lang_en'=>'Belarus',
                'langES'=>'Belarus',
                'langFR'=>'Bélarus',
                'langIT'=>'Bielorussia',
                'langNL'=>'Wit-Rusland',
            ],
            [
                'id'=>116,
                'alpha2'=>'KH',
                'alpha3'=>'KHM',
                'langCS'=>'Kambodža',
                'lang_de'=>'Kambodscha',
                'lang_en'=>'Cambodia',
                'langES'=>'Camboya',
                'langFR'=>'Cambodge',
                'langIT'=>'Cambogia',
                'langNL'=>'Cambodja',
            ],
            [
                'id'=>120,
                'alpha2'=>'CM',
                'alpha3'=>'CMR',
                'langCS'=>'Kamerun',
                'lang_de'=>'Kamerun',
                'lang_en'=>'Cameroon',
                'langES'=>'Camerún',
                'langFR'=>'Cameroun',
                'langIT'=>'Camerun',
                'langNL'=>'Kameroen',
            ],
            [
                'id'=>124,
                'alpha2'=>'CA',
                'alpha3'=>'CAN',
                'langCS'=>'Kanada',
                'lang_de'=>'Kanada',
                'lang_en'=>'Canada',
                'langES'=>'Canadá',
                'langFR'=>'Canada',
                'langIT'=>'Canada',
                'langNL'=>'Canada',
            ],
            [
                'id'=>132,
                'alpha2'=>'CV',
                'alpha3'=>'CPV',
                'langCS'=>'Ostrovy Zeleného mysu',
                'lang_de'=>'Kap Verde',
                'lang_en'=>'Cape Verde',
                'langES'=>'Cabo Verde',
                'langFR'=>'Cap-vert',
                'langIT'=>'Capo Verde',
                'langNL'=>'Kaapverdië',
            ],
            [
                'id'=>136,
                'alpha2'=>'KY',
                'alpha3'=>'CYM',
                'langCS'=>'Kajmanské ostrovy',
                'lang_de'=>'Kaimaninseln',
                'lang_en'=>'Cayman Islands',
                'langES'=>'Islas Caimán',
                'langFR'=>'Îles Caïmanes',
                'langIT'=>'Isole Cayman',
                'langNL'=>'Caymaneilanden',
            ],
            [
                'id'=>140,
                'alpha2'=>'CF',
                'alpha3'=>'CAF',
                'langCS'=>'Středoafrická republika',
                'lang_de'=>'Zentralafrikanische Republik',
                'lang_en'=>'Central African',
                'langES'=>'República Centroafricana',
                'langFR'=>'République Centrafricaine',
                'langIT'=>'Repubblica Centroafricana',
                'langNL'=>'Centraal-Afrikaanse Republiek',
            ],
            [
                'id'=>144,
                'alpha2'=>'LK',
                'alpha3'=>'LKA',
                'langCS'=>'Srí Lanka',
                'lang_de'=>'Sri Lanka',
                'lang_en'=>'Sri Lanka',
                'langES'=>'Sri Lanka',
                'langFR'=>'Sri Lanka',
                'langIT'=>'Sri Lanka',
                'langNL'=>'Sri Lanka',
            ],
            [
                'id'=>148,
                'alpha2'=>'TD',
                'alpha3'=>'TCD',
                'langCS'=>'Čad',
                'lang_de'=>'Tschad',
                'lang_en'=>'Chad',
                'langES'=>'Chad',
                'langFR'=>'Tchad',
                'langIT'=>'Ciad',
                'langNL'=>'Tsjaad',
            ],
            [
                'id'=>152,
                'alpha2'=>'CL',
                'alpha3'=>'CHL',
                'langCS'=>'Chile',
                'lang_de'=>'Chile',
                'lang_en'=>'Chile',
                'langES'=>'Chile',
                'langFR'=>'Chili',
                'langIT'=>'Cile',
                'langNL'=>'Chili',
            ],
            [
                'id'=>156,
                'alpha2'=>'CN',
                'alpha3'=>'CHN',
                'langCS'=>'Čína',
                'lang_de'=>'China',
                'lang_en'=>'China',
                'langES'=>'China',
                'langFR'=>'Chine',
                'langIT'=>'Cina',
                'langNL'=>'China',
            ],
            [
                'id'=>158,
                'alpha2'=>'TW',
                'alpha3'=>'TWN',
                'langCS'=>'Tchajwan',
                'lang_de'=>'Taiwan',
                'lang_en'=>'Taiwan',
                'langES'=>'Taiwán',
                'langFR'=>'Taïwan',
                'langIT'=>'Taiwan',
                'langNL'=>'Taiwan',
            ],
            [
                'id'=>162,
                'alpha2'=>'CX',
                'alpha3'=>'CXR',
                'langCS'=>'Christmas Island',
                'lang_de'=>'Weihnachtsinsel',
                'lang_en'=>'Christmas Island',
                'langES'=>'Isla Navidad',
                'langFR'=>'Île Christmas',
                'langIT'=>'Isola di Natale',
                'langNL'=>'Christmaseiland',
            ],
            [
                'id'=>166,
                'alpha2'=>'CC',
                'alpha3'=>'CCK',
                'langCS'=>'Kokosové ostrovy',
                'lang_de'=>'Kokosinseln',
                'lang_en'=>'Cocos (Keeling) Islands',
                'langES'=>'Islas Cocos (Keeling)',
                'langFR'=>'Îles Cocos (Keeling)',
                'langIT'=>'Isole Cocos',
                'langNL'=>'Cocoseilanden',
            ],
            [
                'id'=>170,
                'alpha2'=>'CO',
                'alpha3'=>'COL',
                'langCS'=>'Kolumbie',
                'lang_de'=>'Kolumbien',
                'lang_en'=>'Colombia',
                'langES'=>'Colombia',
                'langFR'=>'Colombie',
                'langIT'=>'Colombia',
                'langNL'=>'Colombia',
            ],
            [
                'id'=>174,
                'alpha2'=>'KM',
                'alpha3'=>'COM',
                'langCS'=>'Komory',
                'lang_de'=>'Komoren',
                'lang_en'=>'Comoros',
                'langES'=>'Comoros',
                'langFR'=>'Comores',
                'langIT'=>'Comore',
                'langNL'=>'Comoren',
            ],
            [
                'id'=>175,
                'alpha2'=>'YT',
                'alpha3'=>'MYT',
                'langCS'=>'Mayotte',
                'lang_de'=>'Mayotte',
                'lang_en'=>'Mayotte',
                'langES'=>'Mayote',
                'langFR'=>'Mayotte',
                'langIT'=>'Mayotte',
                'langNL'=>'Mayotte',
            ],
            [
                'id'=>178,
                'alpha2'=>'CG',
                'alpha3'=>'COG',
                'langCS'=>'Konžská republika Kongo',
                'lang_de'=>'Republik Kongo',
                'lang_en'=>'Republic of the Congo',
                'langES'=>'Congo',
                'langFR'=>'République du Congo',
                'langIT'=>'Repubblica del Congo',
                'langNL'=>'Republiek Congo',
            ],
            [
                'id'=>180,
                'alpha2'=>'CD',
                'alpha3'=>'COD',
                'langCS'=>'Demokratická republika Kongo Kongo',
                'lang_de'=>'Demokratische Republik Kongo',
                'lang_en'=>'The Democratic Republic Of The Congo',
                'langES'=>'República Democrática del Congo',
                'langFR'=>'République Démocratique du Congo',
                'langIT'=>'Repubblica Democratica del Congo',
                'langNL'=>'Democratische Republiek Congo',
            ],
            [
                'id'=>184,
                'alpha2'=>'CK',
                'alpha3'=>'COK',
                'langCS'=>'Cookovy ostrovy',
                'lang_de'=>'Cookinseln',
                'lang_en'=>'Cook Islands',
                'langES'=>'Islas Cook',
                'langFR'=>'Îles Cook',
                'langIT'=>'Isole Cook',
                'langNL'=>'Cookeilanden',
            ],
            [
                'id'=>188,
                'alpha2'=>'CR',
                'alpha3'=>'CRI',
                'langCS'=>'Kostarika',
                'lang_de'=>'Costa Rica',
                'lang_en'=>'Costa Rica',
                'langES'=>'Costa Rica',
                'langFR'=>'Costa Rica',
                'langIT'=>'Costa Rica',
                'langNL'=>'Costa Rica',
            ],
            [
                'id'=>191,
                'alpha2'=>'HR',
                'alpha3'=>'HRV',
                'langCS'=>'Chorvatsko',
                'lang_de'=>'Kroatien',
                'lang_en'=>'Croatia',
                'langES'=>'Croacia',
                'langFR'=>'Croatie',
                'langIT'=>'Croazia',
                'langNL'=>'Kroatië',
            ],
            [
                'id'=>192,
                'alpha2'=>'CU',
                'alpha3'=>'CUB',
                'langCS'=>'Kuba',
                'lang_de'=>'Kuba',
                'lang_en'=>'Cuba',
                'langES'=>'Cuba',
                'langFR'=>'Cuba',
                'langIT'=>'Cuba',
                'langNL'=>'Cuba',
            ],
            [
                'id'=>196,
                'alpha2'=>'CY',
                'alpha3'=>'CYP',
                'langCS'=>'Kypr',
                'lang_de'=>'Zypern',
                'lang_en'=>'Cyprus',
                'langES'=>'Chipre',
                'langFR'=>'Chypre',
                'langIT'=>'Cipro',
                'langNL'=>'Cyprus',
            ],
            [
                'id'=>203,
                'alpha2'=>'CZ',
                'alpha3'=>'CZE',
                'langCS'=>'Česko',
                'lang_de'=>'Tschechische Republik',
                'lang_en'=>'Czech Republic',
                'langES'=>'Chequia',
                'langFR'=>'République Tchèque',
                'langIT'=>'Repubblica Ceca',
                'langNL'=>'Tsjechië',
            ],
            [
                'id'=>204,
                'alpha2'=>'BJ',
                'alpha3'=>'BEN',
                'langCS'=>'Benin',
                'lang_de'=>'Benin',
                'lang_en'=>'Benin',
                'langES'=>'Benin',
                'langFR'=>'Bénin',
                'langIT'=>'Benin',
                'langNL'=>'Benin',
            ],
            [
                'id'=>208,
                'alpha2'=>'DK',
                'alpha3'=>'DNK',
                'langCS'=>'Dánsko',
                'lang_de'=>'Dänemark',
                'lang_en'=>'Denmark',
                'langES'=>'Dinamarca',
                'langFR'=>'Danemark',
                'langIT'=>'Danimarca',
                'langNL'=>'Denemarken',
            ],
            [
                'id'=>212,
                'alpha2'=>'DM',
                'alpha3'=>'DMA',
                'langCS'=>'Dominika',
                'lang_de'=>'Dominica',
                'lang_en'=>'Dominica',
                'langES'=>'Dominica',
                'langFR'=>'Dominique',
                'langIT'=>'Dominica',
                'langNL'=>'Dominica',
            ],
            [
                'id'=>214,
                'alpha2'=>'DO',
                'alpha3'=>'DOM',
                'langCS'=>'Dominikánská republika',
                'lang_de'=>'Dominikanische Republik',
                'lang_en'=>'Dominican Republic',
                'langES'=>'República Dominicana',
                'langFR'=>'République Dominicaine',
                'langIT'=>'Repubblica Dominicana',
                'langNL'=>'Dominicaanse Republiek',
            ],
            [
                'id'=>218,
                'alpha2'=>'EC',
                'alpha3'=>'ECU',
                'langCS'=>'Ekvádor',
                'lang_de'=>'Ecuador',
                'lang_en'=>'Ecuador',
                'langES'=>'Ecuador',
                'langFR'=>'Équateur',
                'langIT'=>'Ecuador',
                'langNL'=>'Ecuador',
            ],
            [
                'id'=>222,
                'alpha2'=>'SV',
                'alpha3'=>'SLV',
                'langCS'=>'Salvador',
                'lang_de'=>'El Salvador',
                'lang_en'=>'El Salvador',
                'langES'=>'El Salvador',
                'langFR'=>'El Salvador',
                'langIT'=>'El Salvador',
                'langNL'=>'El Salvador',
            ],
            [
                'id'=>226,
                'alpha2'=>'GQ',
                'alpha3'=>'GNQ',
                'langCS'=>'Rovníková Guinea',
                'lang_de'=>'Äquatorialguinea',
                'lang_en'=>'Equatorial Guinea',
                'langES'=>'Guinea Ecuatorial',
                'langFR'=>'Guinée Équatoriale',
                'langIT'=>'Guinea Equatoriale',
                'langNL'=>'Equatoriaal Guinea',
            ],
            [
                'id'=>231,
                'alpha2'=>'ET',
                'alpha3'=>'ETH',
                'langCS'=>'Etiopie',
                'lang_de'=>'Äthiopien',
                'lang_en'=>'Ethiopia',
                'langES'=>'Etiopía',
                'langFR'=>'Éthiopie',
                'langIT'=>'Etiopia',
                'langNL'=>'Ethiopië',
            ],
            [
                'id'=>232,
                'alpha2'=>'ER',
                'alpha3'=>'ERI',
                'langCS'=>'Eritrea',
                'lang_de'=>'Eritrea',
                'lang_en'=>'Eritrea',
                'langES'=>'Eritrea',
                'langFR'=>'Érythrée',
                'langIT'=>'Eritrea',
                'langNL'=>'Eritrea',
            ],
            [
                'id'=>233,
                'alpha2'=>'EE',
                'alpha3'=>'EST',
                'langCS'=>'Estonsko',
                'lang_de'=>'Estland',
                'lang_en'=>'Estonia',
                'langES'=>'Estonia',
                'langFR'=>'Estonie',
                'langIT'=>'Estonia',
                'langNL'=>'Estland',
            ],
            [
                'id'=>234,
                'alpha2'=>'FO',
                'alpha3'=>'FRO',
                'langCS'=>'Faerské ostrovy',
                'lang_de'=>'Färöer',
                'lang_en'=>'Faroe Islands',
                'langES'=>'Islas Faroe',
                'langFR'=>'Îles Féroé',
                'langIT'=>'Isole Faroe',
                'langNL'=>'Faeröer',
            ],
            [
                'id'=>238,
                'alpha2'=>'FK',
                'alpha3'=>'FLK',
                'langCS'=>'Falklandské ostrovy',
                'lang_de'=>'Falklandinseln',
                'lang_en'=>'Falkland Islands',
                'langES'=>'Islas Malvinas',
                'langFR'=>'Îles (malvinas) Falkland',
                'langIT'=>'Isole Falkland',
                'langNL'=>'Falklandeilanden',
            ],
            [
                'id'=>239,
                'alpha2'=>'GS',
                'alpha3'=>'SGS',
                'langCS'=>'Jižní Georgie a Jižní Sandwichovy ostrovy',
                'lang_de'=>'Südgeorgien und die Südlichen Sandwichinseln',
                'lang_en'=>'South Georgia and the South Sandwich Islands',
                'langES'=>'Georgia del Sur e Islas Sandwich del Sur',
                'langFR'=>'Géorgie du Sud et les Îles Sandwich du Sud',
                'langIT'=>'Sud Georgia e Isole Sandwich',
                'langNL'=>'Zuid-Georgië en de Zuidelijke Sandwicheilande',
            ],
            [
                'id'=>242,
                'alpha2'=>'FJ',
                'alpha3'=>'FJI',
                'langCS'=>'Fidži',
                'lang_de'=>'Fidschi',
                'lang_en'=>'Fiji',
                'langES'=>'Fiji',
                'langFR'=>'Fidji',
                'langIT'=>'Fiji',
                'langNL'=>'Fiji',
            ],
            [
                'id'=>246,
                'alpha2'=>'FI',
                'alpha3'=>'FIN',
                'langCS'=>'Finsko',
                'lang_de'=>'Finnland',
                'lang_en'=>'Finland',
                'langES'=>'Finlandia',
                'langFR'=>'Finlande',
                'langIT'=>'Finlandia',
                'langNL'=>'Finland',
            ],
            [
                'id'=>248,
                'alpha2'=>'AX',
                'alpha3'=>'ALA',
                'langCS'=>'Åland Islands',
                'lang_de'=>'Åland-Inseln',
                'lang_en'=>'Åland Islands',
                'langES'=>'IslasÅland',
                'langFR'=>'Îles Åland',
                'langIT'=>'Åland Islands',
                'langNL'=>'Åland Islands',
            ],
            [
                'id'=>250,
                'alpha2'=>'FR',
                'alpha3'=>'FRA',
                'langCS'=>'Francie',
                'lang_de'=>'Frankreich',
                'lang_en'=>'France',
                'langES'=>'Francia',
                'langFR'=>'France',
                'langIT'=>'Francia',
                'langNL'=>'Frankrijk',
            ],
            [
                'id'=>254,
                'alpha2'=>'GF',
                'alpha3'=>'GUF',
                'langCS'=>'Francouzská Guayana',
                'lang_de'=>'Französisch-Guayana',
                'lang_en'=>'French Guiana',
                'langES'=>'Guinea Francesa',
                'langFR'=>'Guyane Française',
                'langIT'=>'Guyana Francese',
                'langNL'=>'Frans-Guyana',
            ],
            [
                'id'=>258,
                'alpha2'=>'PF',
                'alpha3'=>'PYF',
                'langCS'=>'Francouzská Polynésie',
                'lang_de'=>'Französisch-Polynesien',
                'lang_en'=>'French Polynesia',
                'langES'=>'Polinesia Francesa',
                'langFR'=>'Polynésie Française',
                'langIT'=>'Polinesia Francese',
                'langNL'=>'Frans-Polynesië',
            ],
            [
                'id'=>260,
                'alpha2'=>'TF',
                'alpha3'=>'ATF',
                'langCS'=>'Francouzská jižní teritoria',
                'lang_de'=>'Französische Süd- und Antarktisgebiete',
                'lang_en'=>'French Southern Territories',
                'langES'=>'Territorios Sureños de Francia',
                'langFR'=>'Terres Australes Françaises',
                'langIT'=>'Territori Francesi del Sud',
                'langNL'=>'Franse Zuidelijke en Antarctische gebieden',
            ],
            [
                'id'=>262,
                'alpha2'=>'DJ',
                'alpha3'=>'DJI',
                'langCS'=>'Džibutsko',
                'lang_de'=>'Dschibuti',
                'lang_en'=>'Djibouti',
                'langES'=>'Djibouti',
                'langFR'=>'Djibouti',
                'langIT'=>'Gibuti',
                'langNL'=>'Djibouti',
            ],
            [
                'id'=>266,
                'alpha2'=>'GA',
                'alpha3'=>'GAB',
                'langCS'=>'Gabon',
                'lang_de'=>'Gabun',
                'lang_en'=>'Gabon',
                'langES'=>'Gabón',
                'langFR'=>'Gabon',
                'langIT'=>'Gabon',
                'langNL'=>'Gabon',
            ],
            [
                'id'=>268,
                'alpha2'=>'GE',
                'alpha3'=>'GEO',
                'langCS'=>'Gruzínsko',
                'lang_de'=>'Georgien',
                'lang_en'=>'Georgia',
                'langES'=>'Georgia',
                'langFR'=>'Géorgie',
                'langIT'=>'Georgia',
                'langNL'=>'Georgië',
            ],
            [
                'id'=>270,
                'alpha2'=>'GM',
                'alpha3'=>'GMB',
                'langCS'=>'Gambie',
                'lang_de'=>'Gambia',
                'lang_en'=>'Gambia',
                'langES'=>'Gambia',
                'langFR'=>'Gambie',
                'langIT'=>'Gambia',
                'langNL'=>'Gambia',
            ],
            [
                'id'=>275,
                'alpha2'=>'PS',
                'alpha3'=>'PSE',
                'langCS'=>'Palestinská území',
                'lang_de'=>'Palästinensische Autonomiegebiete',
                'lang_en'=>'Occupied Palestinian Territory',
                'langES'=>'Palestina',
                'langFR'=>'Territoire Palestinien Occupé',
                'langIT'=>'Territori Palestinesi Occupati',
                'langNL'=>'Palestina',
            ],
            [
                'id'=>276,
                'alpha2'=>'DE',
                'alpha3'=>'DEU',
                'langCS'=>'Německo',
                'lang_de'=>'Deutschland',
                'lang_en'=>'Germany',
                'langES'=>'Alemania',
                'langFR'=>'Allemagne',
                'langIT'=>'Germania',
                'langNL'=>'Duitsland',
            ],
            [
                'id'=>288,
                'alpha2'=>'GH',
                'alpha3'=>'GHA',
                'langCS'=>'Ghana',
                'lang_de'=>'Ghana',
                'lang_en'=>'Ghana',
                'langES'=>'Ghana',
                'langFR'=>'Ghana',
                'langIT'=>'Ghana',
                'langNL'=>'Ghana',
            ],
            [
                'id'=>292,
                'alpha2'=>'GI',
                'alpha3'=>'GIB',
                'langCS'=>'Gibraltar',
                'lang_de'=>'Gibraltar',
                'lang_en'=>'Gibraltar',
                'langES'=>'Gibraltar',
                'langFR'=>'Gibraltar',
                'langIT'=>'Gibilterra',
                'langNL'=>'Gibraltar',
            ],
            [
                'id'=>296,
                'alpha2'=>'KI',
                'alpha3'=>'KIR',
                'langCS'=>'Kiribati',
                'lang_de'=>'Kiribati',
                'lang_en'=>'Kiribati',
                'langES'=>'Kiribati',
                'langFR'=>'Kiribati',
                'langIT'=>'Kiribati',
                'langNL'=>'Kiribati',
            ],
        ];

        Country::insert($countries);
        $countries = [
            [
                'id'=>300,
                'alpha2'=>'GR',
                'alpha3'=>'GRC',
                'langCS'=>'Řecko',
                'lang_de'=>'Griechenland',
                'lang_en'=>'Greece',
                'langES'=>'Grecia',
                'langFR'=>'Grèce',
                'langIT'=>'Grecia',
                'langNL'=>'Griekenland',
            ],
            [
                'id'=>304,
                'alpha2'=>'GL',
                'alpha3'=>'GRL',
                'langCS'=>'Grónsko',
                'lang_de'=>'Grönland',
                'lang_en'=>'Greenland',
                'langES'=>'Groenlandia',
                'langFR'=>'Groenland',
                'langIT'=>'Groenlandia',
                'langNL'=>'Groenland',
            ],
            [
                'id'=>308,
                'alpha2'=>'GD',
                'alpha3'=>'GRD',
                'langCS'=>'Grenada',
                'lang_de'=>'Grenada',
                'lang_en'=>'Grenada',
                'langES'=>'Granada',
                'langFR'=>'Grenade',
                'langIT'=>'Grenada',
                'langNL'=>'Grenada',
            ],
            [
                'id'=>312,
                'alpha2'=>'GP',
                'alpha3'=>'GLP',
                'langCS'=>'Guadeloupe',
                'lang_de'=>'Guadeloupe',
                'lang_en'=>'Guadeloupe',
                'langES'=>'Guadalupe',
                'langFR'=>'Guadeloupe',
                'langIT'=>'Guadalupa',
                'langNL'=>'Guadeloupe',
            ],
            [
                'id'=>316,
                'alpha2'=>'GU',
                'alpha3'=>'GUM',
                'langCS'=>'Guam',
                'lang_de'=>'Guam',
                'lang_en'=>'Guam',
                'langES'=>'Guam',
                'langFR'=>'Guam',
                'langIT'=>'Guam',
                'langNL'=>'Guam',
            ],
            [
                'id'=>320,
                'alpha2'=>'GT',
                'alpha3'=>'GTM',
                'langCS'=>'Guatemala',
                'lang_de'=>'Guatemala',
                'lang_en'=>'Guatemala',
                'langES'=>'Guatemala',
                'langFR'=>'Guatemala',
                'langIT'=>'Guatemala',
                'langNL'=>'Guatemala',
            ],
            [
                'id'=>324,
                'alpha2'=>'GN',
                'alpha3'=>'GIN',
                'langCS'=>'Guinea',
                'lang_de'=>'Guinea',
                'lang_en'=>'Guinea',
                'langES'=>'Guinea',
                'langFR'=>'Guinée',
                'langIT'=>'Guinea',
                'langNL'=>'Guinee',
            ],
            [
                'id'=>328,
                'alpha2'=>'GY',
                'alpha3'=>'GUY',
                'langCS'=>'Guyana',
                'lang_de'=>'Guyana',
                'lang_en'=>'Guyana',
                'langES'=>'Guayana',
                'langFR'=>'Guyana',
                'langIT'=>'Guyana',
                'langNL'=>'Guyana',
            ],
            [
                'id'=>332,
                'alpha2'=>'HT',
                'alpha3'=>'HTI',
                'langCS'=>'Haiti',
                'lang_de'=>'Haiti',
                'lang_en'=>'Haiti',
                'langES'=>'Haití',
                'langFR'=>'Haïti',
                'langIT'=>'Haiti',
                'langNL'=>'Haiti',
            ],
            [
                'id'=>334,
                'alpha2'=>'HM',
                'alpha3'=>'HMD',
                'langCS'=>'Heardův ostrov a McDonaldovy ostrovy',
                'lang_de'=>'Heard und McDonaldinseln',
                'lang_en'=>'Heard Island and McDonald Islands',
                'langES'=>'Islas Heard e Islas McDonald',
                'langFR'=>'Îles Heard et Mcdonald',
                'langIT'=>'Isola Heard e Isole McDonald',
                'langNL'=>'Heard- en McDonaldeilanden',
            ],
            [
                'id'=>336,
                'alpha2'=>'VA',
                'alpha3'=>'VAT',
                'langCS'=>'Vatikán',
                'lang_de'=>'Vatikanstadt',
                'lang_en'=>'Vatican City State',
                'langES'=>'Estado Vaticano',
                'langFR'=>'Saint-Siège (état de la Cité du Vatican)',
                'langIT'=>'Città del Vaticano',
                'langNL'=>'Vaticaanstad',
            ],
            [
                'id'=>340,
                'alpha2'=>'HN',
                'alpha3'=>'HND',
                'langCS'=>'Honduras',
                'lang_de'=>'Honduras',
                'lang_en'=>'Honduras',
                'langES'=>'Honduras',
                'langFR'=>'Honduras',
                'langIT'=>'Honduras',
                'langNL'=>'Honduras',
            ],
            [
                'id'=>344,
                'alpha2'=>'HK',
                'alpha3'=>'HKG',
                'langCS'=>'Hong Kong',
                'lang_de'=>'Hongkong',
                'lang_en'=>'Hong Kong',
                'langES'=>'Hong Kong',
                'langFR'=>'Hong-Kong',
                'langIT'=>'Hong Kong',
                'langNL'=>'Hongkong',
            ],
            [
                'id'=>348,
                'alpha2'=>'HU',
                'alpha3'=>'HUN',
                'langCS'=>'Maďarsko',
                'lang_de'=>'Ungarn',
                'lang_en'=>'Hungary',
                'langES'=>'Hungría',
                'langFR'=>'Hongrie',
                'langIT'=>'Ungheria',
                'langNL'=>'Hongarije',
            ],
            [
                'id'=>352,
                'alpha2'=>'IS',
                'alpha3'=>'ISL',
                'langCS'=>'Island',
                'lang_de'=>'Island',
                'lang_en'=>'Iceland',
                'langES'=>'Islandia',
                'langFR'=>'Islande',
                'langIT'=>'Islanda',
                'langNL'=>'IJsland',
            ],
            [
                'id'=>356,
                'alpha2'=>'IN',
                'alpha3'=>'IND',
                'langCS'=>'Indie',
                'lang_de'=>'Indien',
                'lang_en'=>'India',
                'langES'=>'India',
                'langFR'=>'Inde',
                'langIT'=>'India',
                'langNL'=>'India',
            ],
            [
                'id'=>360,
                'alpha2'=>'ID',
                'alpha3'=>'IDN',
                'langCS'=>'Indonésie',
                'lang_de'=>'Indonesien',
                'lang_en'=>'Indonesia',
                'langES'=>'Indonesia',
                'langFR'=>'Indonésie',
                'langIT'=>'Indonesia',
                'langNL'=>'Indonesië',
            ],
            [
                'id'=>364,
                'alpha2'=>'IR',
                'alpha3'=>'IRN',
                'langCS'=>'Írán',
                'lang_de'=>'Islamische Republik Iran',
                'lang_en'=>'Islamic Republic of Iran',
                'langES'=>'Irán',
                'langFR'=>'République Islamique d',
                'langIT'=>'Iran',
                'langNL'=>'Iran',
            ],
            [
                'id'=>368,
                'alpha2'=>'IQ',
                'alpha3'=>'IRQ',
                'langCS'=>'Irák',
                'lang_de'=>'Irak',
                'lang_en'=>'Iraq',
                'langES'=>'Irak',
                'langFR'=>'Iraq',
                'langIT'=>'Iraq',
                'langNL'=>'Irak',
            ],
            [
                'id'=>372,
                'alpha2'=>'IE',
                'alpha3'=>'IRL',
                'langCS'=>'Irsko',
                'lang_de'=>'Irland',
                'lang_en'=>'Ireland',
                'langES'=>'Irlanda',
                'langFR'=>'Irlande',
                'langIT'=>'Eire',
                'langNL'=>'Ierland',
            ],
            [
                'id'=>376,
                'alpha2'=>'IL',
                'alpha3'=>'ISR',
                'langCS'=>'Izrael',
                'lang_de'=>'Israel',
                'lang_en'=>'Israel',
                'langES'=>'Israel',
                'langFR'=>'Israël',
                'langIT'=>'Israele',
                'langNL'=>'Israël',
            ],
            [
                'id'=>380,
                'alpha2'=>'IT',
                'alpha3'=>'ITA',
                'langCS'=>'Itálie',
                'lang_de'=>'Italien',
                'lang_en'=>'Italy',
                'langES'=>'Italia',
                'langFR'=>'Italie',
                'langIT'=>'Italia',
                'langNL'=>'Italië',
            ],
            [
                'id'=>384,
                'alpha2'=>'CI',
                'alpha3'=>'CIV',
                'langCS'=>'Pobřeží slonoviny',
                'lang_de'=>'Côte d',
                'lang_en'=>'Ivoire',
                'langES'=>'Côte d',
                'langFR'=>'Ivoire',
                'langIT'=>'Costa de Marfil',
                'langNL'=>'Côte de Ivoire',
            ],
            [
                'id'=>388,
                'alpha2'=>'JM',
                'alpha3'=>'JAM',
                'langCS'=>'Jamajka',
                'lang_de'=>'Jamaika',
                'lang_en'=>'Jamaica',
                'langES'=>'Jamaica',
                'langFR'=>'Jamaïque',
                'langIT'=>'Giamaica',
                'langNL'=>'Jamaica',
            ],
            [
                'id'=>392,
                'alpha2'=>'JP',
                'alpha3'=>'JPN',
                'langCS'=>'Japonsko',
                'lang_de'=>'Japan',
                'lang_en'=>'Japan',
                'langES'=>'Japón',
                'langFR'=>'Japon',
                'langIT'=>'Giappone',
                'langNL'=>'Japan',
            ],
            [
                'id'=>398,
                'alpha2'=>'KZ',
                'alpha3'=>'KAZ',
                'langCS'=>'Kazachstán',
                'lang_de'=>'Kasachstan',
                'lang_en'=>'Kazakhstan',
                'langES'=>'Kazajstán',
                'langFR'=>'Kazakhstan',
                'langIT'=>'Kazakhistan',
                'langNL'=>'Kazachstan',
            ],
            [
                'id'=>400,
                'alpha2'=>'JO',
                'alpha3'=>'JOR',
                'langCS'=>'Jordánsko',
                'lang_de'=>'Jordanien',
                'lang_en'=>'Jordan',
                'langES'=>'Jordania',
                'langFR'=>'Jordanie',
                'langIT'=>'Giordania',
                'langNL'=>'Jordanië',
            ],
            [
                'id'=>404,
                'alpha2'=>'KE',
                'alpha3'=>'KEN',
                'langCS'=>'Keňa',
                'lang_de'=>'Kenia',
                'lang_en'=>'Kenya',
                'langES'=>'Kenia',
                'langFR'=>'Kenya',
                'langIT'=>'Kenya',
                'langNL'=>'Kenia',
            ],
            [
                'id'=>408,
                'alpha2'=>'KP',
                'alpha3'=>'PRK',
                'langCS'=>'Severní Korea',
                'lang_de'=>'Demokratische Volksrepublik Korea',
                'lang_en'=>'Democratic People',
                'langES'=>'s Republic of Korea',
                'langFR'=>'Corea',
                'langIT'=>'République Populaire Démocratique de Corée',
                'langNL'=>'Corea del Nord\'Noord-Korea',
            ],
            [
                'id'=>410,
                'alpha2'=>'KR',
                'alpha3'=>'KOR',
                'langCS'=>'Jižní Korea',
                'lang_de'=>'Republik Korea',
                'lang_en'=>'Republic of Korea',
                'langES'=>'Corea',
                'langFR'=>'République de Corée',
                'langIT'=>'Corea del Sud',
                'langNL'=>'Zuid-Korea',
            ],
            [
                'id'=>414,
                'alpha2'=>'KW',
                'alpha3'=>'KWT',
                'langCS'=>'Kuvajt',
                'lang_de'=>'Kuwait',
                'lang_en'=>'Kuwait',
                'langES'=>'Kuwait',
                'langFR'=>'Koweït',
                'langIT'=>'Kuwait',
                'langNL'=>'Koeweit',
            ],
            [
                'id'=>417,
                'alpha2'=>'KG',
                'alpha3'=>'KGZ',
                'langCS'=>'Kyrgyzstán',
                'lang_de'=>'Kirgisistan',
                'lang_en'=>'Kyrgyzstan',
                'langES'=>'Kirgistán',
                'langFR'=>'Kirghizistan',
                'langIT'=>'Kirghizistan',
                'langNL'=>'Kirgizië',
            ],
            [
                'id'=>418,
                'alpha2'=>'LA',
                'alpha3'=>'LAO',
                'langCS'=>'Laos',
                'lang_de'=>'Demokratische Volksrepublik Laos',
                'lang_en'=>'Lao People',
                'langES'=>'s Democratic Republic',
                'langFR'=>'Laos',
                'langIT'=>'République Démocratique Populaire Lao',
                'langNL'=>'Laos',
            ],
            [
                'id'=>422,
                'alpha2'=>'LB',
                'alpha3'=>'LBN',
                'langCS'=>'Libanon',
                'lang_de'=>'Libanon',
                'lang_en'=>'Lebanon',
                'langES'=>'Líbano',
                'langFR'=>'Liban',
                'langIT'=>'Libano',
                'langNL'=>'Libanon',
            ],
            [
                'id'=>426,
                'alpha2'=>'LS',
                'alpha3'=>'LSO',
                'langCS'=>'Lesotho',
                'lang_de'=>'Lesotho',
                'lang_en'=>'Lesotho',
                'langES'=>'Lesoto',
                'langFR'=>'Lesotho',
                'langIT'=>'Lesotho',
                'langNL'=>'Lesotho',
            ],
            [
                'id'=>428,
                'alpha2'=>'LV',
                'alpha3'=>'LVA',
                'langCS'=>'Lotyšsko',
                'lang_de'=>'Lettland',
                'lang_en'=>'Latvia',
                'langES'=>'Letonia',
                'langFR'=>'Lettonie',
                'langIT'=>'Lettonia',
                'langNL'=>'Letland',
            ],
            [
                'id'=>430,
                'alpha2'=>'LR',
                'alpha3'=>'LBR',
                'langCS'=>'Libérie',
                'lang_de'=>'Liberia',
                'lang_en'=>'Liberia',
                'langES'=>'Liberia',
                'langFR'=>'Libéria',
                'langIT'=>'Liberia',
                'langNL'=>'Liberia',
            ],
            [
                'id'=>434,
                'alpha2'=>'LY',
                'alpha3'=>'LBY',
                'langCS'=>'Libye',
                'lang_de'=>'Libysch-Arabische Dschamahirija',
                'lang_en'=>'Libyan Arab Jamahiriya',
                'langES'=>'Libia',
                'langFR'=>'Jamahiriya Arabe Libyenne',
                'langIT'=>'Libia',
                'langNL'=>'Libië',
            ],
            [
                'id'=>438,
                'alpha2'=>'LI',
                'alpha3'=>'LIE',
                'langCS'=>'Lichtenštejnsko',
                'lang_de'=>'Liechtenstein',
                'lang_en'=>'Liechtenstein',
                'langES'=>'Liechtenstein',
                'langFR'=>'Liechtenstein',
                'langIT'=>'Liechtenstein',
                'langNL'=>'Liechtenstein',
            ],
            [
                'id'=>440,
                'alpha2'=>'LT',
                'alpha3'=>'LTU',
                'langCS'=>'Litva',
                'lang_de'=>'Litauen',
                'lang_en'=>'Lithuania',
                'langES'=>'Lituania',
                'langFR'=>'Lituanie',
                'langIT'=>'Lituania',
                'langNL'=>'Litouwen',
            ],
            [
                'id'=>442,
                'alpha2'=>'LU',
                'alpha3'=>'LUX',
                'langCS'=>'Lucembursko',
                'lang_de'=>'Luxemburg',
                'lang_en'=>'Luxembourg',
                'langES'=>'Luxemburgo',
                'langFR'=>'Luxembourg',
                'langIT'=>'Lussemburgo',
                'langNL'=>'Groothertogdom Luxemburg',
            ],
            [
                'id'=>446,
                'alpha2'=>'MO',
                'alpha3'=>'MAC',
                'langCS'=>'Macao',
                'lang_de'=>'Macao',
                'lang_en'=>'Macao',
                'langES'=>'Macao',
                'langFR'=>'Macao',
                'langIT'=>'Macao',
                'langNL'=>'Macao',
            ],
            [
                'id'=>450,
                'alpha2'=>'MG',
                'alpha3'=>'MDG',
                'langCS'=>'Madagaskar',
                'lang_de'=>'Madagaskar',
                'lang_en'=>'Madagascar',
                'langES'=>'Madagascar',
                'langFR'=>'Madagascar',
                'langIT'=>'Madagascar',
                'langNL'=>'Madagaskar',
            ],
            [
                'id'=>454,
                'alpha2'=>'MW',
                'alpha3'=>'MWI',
                'langCS'=>'Malawi',
                'lang_de'=>'Malawi',
                'lang_en'=>'Malawi',
                'langES'=>'Malawi',
                'langFR'=>'Malawi',
                'langIT'=>'Malawi',
                'langNL'=>'Malawi',
            ],
            [
                'id'=>458,
                'alpha2'=>'MY',
                'alpha3'=>'MYS',
                'langCS'=>'Malajsie',
                'lang_de'=>'Malaysia',
                'lang_en'=>'Malaysia',
                'langES'=>'Malasia',
                'langFR'=>'Malaisie',
                'langIT'=>'Malesia',
                'langNL'=>'Maleisië',
            ],
            [
                'id'=>462,
                'alpha2'=>'MV',
                'alpha3'=>'MDV',
                'langCS'=>'Maledivy',
                'lang_de'=>'Malediven',
                'lang_en'=>'Maldives',
                'langES'=>'Maldivas',
                'langFR'=>'Maldives',
                'langIT'=>'Maldive',
                'langNL'=>'Maldiven',
            ],
            [
                'id'=>466,
                'alpha2'=>'ML',
                'alpha3'=>'MLI',
                'langCS'=>'Mali',
                'lang_de'=>'Mali',
                'lang_en'=>'Mali',
                'langES'=>'Mali',
                'langFR'=>'Mali',
                'langIT'=>'Mali',
                'langNL'=>'Mali',
            ],
            [
                'id'=>470,
                'alpha2'=>'MT',
                'alpha3'=>'MLT',
                'langCS'=>'Malta',
                'lang_de'=>'Malta',
                'lang_en'=>'Malta',
                'langES'=>'Malta',
                'langFR'=>'Malte',
                'langIT'=>'Malta',
                'langNL'=>'Malta',
            ],
            [
                'id'=>474,
                'alpha2'=>'MQ',
                'alpha3'=>'MTQ',
                'langCS'=>'Martinik',
                'lang_de'=>'Martinique',
                'lang_en'=>'Martinique',
                'langES'=>'Martinica',
                'langFR'=>'Martinique',
                'langIT'=>'Martinica',
                'langNL'=>'Martinique',
            ],
            [
                'id'=>478,
                'alpha2'=>'MR',
                'alpha3'=>'MRT',
                'langCS'=>'Mauretánie',
                'lang_de'=>'Mauretanien',
                'lang_en'=>'Mauritania',
                'langES'=>'Mauritania',
                'langFR'=>'Mauritanie',
                'langIT'=>'Mauritania',
                'langNL'=>'Mauritanië',
            ],
            [
                'id'=>480,
                'alpha2'=>'MU',
                'alpha3'=>'MUS',
                'langCS'=>'Mauricius',
                'lang_de'=>'Mauritius',
                'lang_en'=>'Mauritius',
                'langES'=>'Mauricio',
                'langFR'=>'Maurice',
                'langIT'=>'Maurizius',
                'langNL'=>'Mauritius',
            ],
            [
                'id'=>484,
                'alpha2'=>'MX',
                'alpha3'=>'MEX',
                'langCS'=>'Mexiko',
                'lang_de'=>'Mexiko',
                'lang_en'=>'Mexico',
                'langES'=>'México',
                'langFR'=>'Mexique',
                'langIT'=>'Messico',
                'langNL'=>'Mexico',
            ],
            [
                'id'=>492,
                'alpha2'=>'MC',
                'alpha3'=>'MCO',
                'langCS'=>'Monako',
                'lang_de'=>'Monaco',
                'lang_en'=>'Monaco',
                'langES'=>'Mónaco',
                'langFR'=>'Monaco',
                'langIT'=>'Monaco',
                'langNL'=>'Monaco',
            ],
            [
                'id'=>496,
                'alpha2'=>'MN',
                'alpha3'=>'MNG',
                'langCS'=>'Mongolsko',
                'lang_de'=>'Mongolei',
                'lang_en'=>'Mongolia',
                'langES'=>'Mongolia',
                'langFR'=>'Mongolie',
                'langIT'=>'Mongolia',
                'langNL'=>'Mongolië',
            ],
            [
                'id'=>498,
                'alpha2'=>'MD',
                'alpha3'=>'MDA',
                'langCS'=>'Moldavsko',
                'lang_de'=>'Moldawien',
                'lang_en'=>'Republic of Moldova',
                'langES'=>'Moldavia',
                'langFR'=>'République de Moldova',
                'langIT'=>'Moldavia',
                'langNL'=>'Republiek Moldavië',
            ],
            [
                'id'=>500,
                'alpha2'=>'MS',
                'alpha3'=>'MSR',
                'langCS'=>'Montserrat',
                'lang_de'=>'Montserrat',
                'lang_en'=>'Montserrat',
                'langES'=>'Montserrat',
                'langFR'=>'Montserrat',
                'langIT'=>'Montserrat',
                'langNL'=>'Montserrat',
            ],
            [
                'id'=>504,
                'alpha2'=>'MA',
                'alpha3'=>'MAR',
                'langCS'=>'Maroko',
                'lang_de'=>'Marokko',
                'lang_en'=>'Morocco',
                'langES'=>'Marruecos',
                'langFR'=>'Maroc',
                'langIT'=>'Marocco',
                'langNL'=>'Marokko',
            ],
            [
                'id'=>508,
                'alpha2'=>'MZ',
                'alpha3'=>'MOZ',
                'langCS'=>'Mosambik',
                'lang_de'=>'Mosambik',
                'lang_en'=>'Mozambique',
                'langES'=>'Mozambique',
                'langFR'=>'Mozambique',
                'langIT'=>'Mozambico',
                'langNL'=>'Mozambique',
            ],
            [
                'id'=>512,
                'alpha2'=>'OM',
                'alpha3'=>'OMN',
                'langCS'=>'Omán',
                'lang_de'=>'Oman',
                'lang_en'=>'Oman',
                'langES'=>'Omán',
                'langFR'=>'Oman',
                'langIT'=>'Oman',
                'langNL'=>'Oman',
            ],
            [
                'id'=>516,
                'alpha2'=>'NA',
                'alpha3'=>'NAM',
                'langCS'=>'Namíbie',
                'lang_de'=>'Namibia',
                'lang_en'=>'Namibia',
                'langES'=>'Namibia',
                'langFR'=>'Namibie',
                'langIT'=>'Namibia',
                'langNL'=>'Namibië',
            ],
            [
                'id'=>520,
                'alpha2'=>'NR',
                'alpha3'=>'NRU',
                'langCS'=>'Nauru',
                'lang_de'=>'Nauru',
                'lang_en'=>'Nauru',
                'langES'=>'Nauru',
                'langFR'=>'Nauru',
                'langIT'=>'Nauru',
                'langNL'=>'Nauru',
            ],
            [
                'id'=>524,
                'alpha2'=>'NP',
                'alpha3'=>'NPL',
                'langCS'=>'Nepál',
                'lang_de'=>'Nepal',
                'lang_en'=>'Nepal',
                'langES'=>'Nepal',
                'langFR'=>'Népal',
                'langIT'=>'Nepal',
                'langNL'=>'Nepal',
            ],
            [
                'id'=>528,
                'alpha2'=>'NL',
                'alpha3'=>'NLD',
                'langCS'=>'Nizozemsko',
                'lang_de'=>'Niederlande',
                'lang_en'=>'Netherlands',
                'langES'=>'Holanda',
                'langFR'=>'Pays-Bas',
                'langIT'=>'Paesi Bassi',
                'langNL'=>'Nederland',
            ],
            [
                'id'=>530,
                'alpha2'=>'AN',
                'alpha3'=>'ANT',
                'langCS'=>'Nizozemské Antily',
                'lang_de'=>'Niederländische Antillen',
                'lang_en'=>'Netherlands Antilles',
                'langES'=>'Antillas Holandesas',
                'langFR'=>'Antilles Néerlandaises',
                'langIT'=>'Antille Olandesi',
                'langNL'=>'Nederlandse Antillen',
            ],
            [
                'id'=>533,
                'alpha2'=>'AW',
                'alpha3'=>'ABW',
                'langCS'=>'Aruba',
                'lang_de'=>'Aruba',
                'lang_en'=>'Aruba',
                'langES'=>'Aruba',
                'langFR'=>'Aruba',
                'langIT'=>'Aruba',
                'langNL'=>'Aruba',
            ],
            [
                'id'=>540,
                'alpha2'=>'NC',
                'alpha3'=>'NCL',
                'langCS'=>'Nová Kaledonie',
                'lang_de'=>'Neukaledonien',
                'lang_en'=>'New Caledonia',
                'langES'=>'Nueva Caledonia',
                'langFR'=>'Nouvelle-Calédonie',
                'langIT'=>'Nuova Caledonia',
                'langNL'=>'Nieuw-Caledonië',
            ],
            [
                'id'=>548,
                'alpha2'=>'VU',
                'alpha3'=>'VUT',
                'langCS'=>'Vanuatu',
                'lang_de'=>'Vanuatu',
                'lang_en'=>'Vanuatu',
                'langES'=>'Vanuatu',
                'langFR'=>'Vanuatu',
                'langIT'=>'Vanuatu',
                'langNL'=>'Vanuatu',
            ],
            [
                'id'=>554,
                'alpha2'=>'NZ',
                'alpha3'=>'NZL',
                'langCS'=>'Nový Zéland',
                'lang_de'=>'Neuseeland',
                'lang_en'=>'New Zealand',
                'langES'=>'Nueva Zelanda',
                'langFR'=>'Nouvelle-Zélande',
                'langIT'=>'Nuova Zelanda',
                'langNL'=>'Nieuw-Zeeland',
            ],
            [
                'id'=>558,
                'alpha2'=>'NI',
                'alpha3'=>'NIC',
                'langCS'=>'Nikaragua',
                'lang_de'=>'Nicaragua',
                'lang_en'=>'Nicaragua',
                'langES'=>'Nicaragua',
                'langFR'=>'Nicaragua',
                'langIT'=>'Nicaragua',
                'langNL'=>'Nicaragua',
            ],
            [
                'id'=>562,
                'alpha2'=>'NE',
                'alpha3'=>'NER',
                'langCS'=>'Niger',
                'lang_de'=>'Niger',
                'lang_en'=>'Niger',
                'langES'=>'Níger',
                'langFR'=>'Niger',
                'langIT'=>'Niger',
                'langNL'=>'Niger',
            ],
            [
                'id'=>566,
                'alpha2'=>'NG',
                'alpha3'=>'NGA',
                'langCS'=>'Nigérie',
                'lang_de'=>'Nigeria',
                'lang_en'=>'Nigeria',
                'langES'=>'Nigeria',
                'langFR'=>'Nigéria',
                'langIT'=>'Nigeria',
                'langNL'=>'Nigeria',
            ],
            [
                'id'=>570,
                'alpha2'=>'NU',
                'alpha3'=>'NIU',
                'langCS'=>'Niue',
                'lang_de'=>'Niue',
                'lang_en'=>'Niue',
                'langES'=>'Niue',
                'langFR'=>'Niué',
                'langIT'=>'Niue',
                'langNL'=>'Niue',
            ],
            [
                'id'=>574,
                'alpha2'=>'NF',
                'alpha3'=>'NFK',
                'langCS'=>'Norfolk Island',
                'lang_de'=>'Norfolkinsel',
                'lang_en'=>'Norfolk Island',
                'langES'=>'Islas Norfolk',
                'langFR'=>'Île Norfolk',
                'langIT'=>'Isola Norfolk',
                'langNL'=>'Norfolkeiland',
            ],
            [
                'id'=>578,
                'alpha2'=>'NO',
                'alpha3'=>'NOR',
                'langCS'=>'Norsko',
                'lang_de'=>'Norwegen',
                'lang_en'=>'Norway',
                'langES'=>'Noruega',
                'langFR'=>'Norvège',
                'langIT'=>'Norvegia',
                'langNL'=>'Noorwegen',
            ],
            [
                'id'=>580,
                'alpha2'=>'MP',
                'alpha3'=>'MNP',
                'langCS'=>'Severomariánské ostrovy',
                'lang_de'=>'Nördliche Marianen',
                'lang_en'=>'Northern Mariana Islands',
                'langES'=>'Islas de Norte-Mariana',
                'langFR'=>'Îles Mariannes du Nord',
                'langIT'=>'Isole Marianne Settentrionali',
                'langNL'=>'Noordelijke Marianen',
            ],
            [
                'id'=>581,
                'alpha2'=>'UM',
                'alpha3'=>'UMI',
                'langCS'=>'United States Minor Outlying Islands',
                'lang_de'=>'Amerikanisch-Ozeanien',
                'lang_en'=>'United States Minor Outlying Islands',
                'langES'=>'Islas Ultramarinas de Estados Unidos',
                'langFR'=>'Îles Mineures Éloignées des États-Unis',
                'langIT'=>'Isole Minori degli Stati Uniti d',
                'langNL'=>'AmericaUnited States Minor Outlying Eilanden',
            ],
            [
                'id'=>583,
                'alpha2'=>'FM',
                'alpha3'=>'FSM',
                'langCS'=>'Mikronésie',
                'lang_de'=>'Mikronesien',
                'lang_en'=>'Federated States of Micronesia',
                'langES'=>'Micronesia',
                'langFR'=>'États Fédérés de Micronésie',
                'langIT'=>'Stati Federati della Micronesia',
                'langNL'=>'Micronesië',
            ],
            [
                'id'=>584,
                'alpha2'=>'MH',
                'alpha3'=>'MHL',
                'langCS'=>'Marshallovy ostrovy',
                'lang_de'=>'Marshallinseln',
                'lang_en'=>'Marshall Islands',
                'langES'=>'Islas Marshall',
                'langFR'=>'Îles Marshall',
                'langIT'=>'Isole Marshall',
                'langNL'=>'Marshalleilanden',
            ],
            [
                'id'=>585,
                'alpha2'=>'PW',
                'alpha3'=>'PLW',
                'langCS'=>'Palau',
                'lang_de'=>'Palau',
                'lang_en'=>'Palau',
                'langES'=>'Palau',
                'langFR'=>'Palaos',
                'langIT'=>'Palau',
                'langNL'=>'Palau',
            ],
            [
                'id'=>586,
                'alpha2'=>'PK',
                'alpha3'=>'PAK',
                'langCS'=>'Pakistán',
                'lang_de'=>'Pakistan',
                'lang_en'=>'Pakistan',
                'langES'=>'Pakistán',
                'langFR'=>'Pakistan',
                'langIT'=>'Pakistan',
                'langNL'=>'Pakistan',
            ],
            [
                'id'=>591,
                'alpha2'=>'PA',
                'alpha3'=>'PAN',
                'langCS'=>'Panama',
                'lang_de'=>'Panama',
                'lang_en'=>'Panama',
                'langES'=>'Panamá',
                'langFR'=>'Panama',
                'langIT'=>'Panamá',
                'langNL'=>'Panama',
            ],
            [
                'id'=>598,
                'alpha2'=>'PG',
                'alpha3'=>'PNG',
                'langCS'=>'Papua Nová Guinea',
                'lang_de'=>'Papua-Neuguinea',
                'lang_en'=>'Papua New Guinea',
                'langES'=>'Papúa Nueva Guinea',
                'langFR'=>'Papouasie-Nouvelle-Guinée',
                'langIT'=>'Papua Nuova Guinea',
                'langNL'=>'Papoea-Nieuw-Guinea',
            ],

        ];

        Country::insert($countries);
        $countries = [
            [
                'id'=>600,
                'alpha2'=>'PY',
                'alpha3'=>'PRY',
                'langCS'=>'Paraguay',
                'lang_de'=>'Paraguay',
                'lang_en'=>'Paraguay',
                'langES'=>'Paraguay',
                'langFR'=>'Paraguay',
                'langIT'=>'Paraguay',
                'langNL'=>'Paraguay',
            ],
            [
                'id'=>604,
                'alpha2'=>'PE',
                'alpha3'=>'PER',
                'langCS'=>'Peru',
                'lang_de'=>'Peru',
                'lang_en'=>'Peru',
                'langES'=>'Perú',
                'langFR'=>'Pérou',
                'langIT'=>'Perù',
                'langNL'=>'Peru',
            ],
            [
                'id'=>608,
                'alpha2'=>'PH',
                'alpha3'=>'PHL',
                'langCS'=>'Filipíny',
                'lang_de'=>'Philippinen',
                'lang_en'=>'Philippines',
                'langES'=>'Filipinas',
                'langFR'=>'Philippines',
                'langIT'=>'Filippine',
                'langNL'=>'Filippijnen',
            ],
            [
                'id'=>612,
                'alpha2'=>'PN',
                'alpha3'=>'PCN',
                'langCS'=>'Pitcairn',
                'lang_de'=>'Pitcairninseln',
                'lang_en'=>'Pitcairn',
                'langES'=>'Pitcairn',
                'langFR'=>'Pitcairn',
                'langIT'=>'Pitcairn',
                'langNL'=>'Pitcairneilanden',
            ],
            [
                'id'=>616,
                'alpha2'=>'PL',
                'alpha3'=>'POL',
                'langCS'=>'Polsko',
                'lang_de'=>'Polen',
                'lang_en'=>'Poland',
                'langES'=>'Polonia',
                'langFR'=>'Pologne',
                'langIT'=>'Polonia',
                'langNL'=>'Polen',
            ],
            [
                'id'=>620,
                'alpha2'=>'PT',
                'alpha3'=>'PRT',
                'langCS'=>'Portugalsko',
                'lang_de'=>'Portugal',
                'lang_en'=>'Portugal',
                'langES'=>'Portugal',
                'langFR'=>'Portugal',
                'langIT'=>'Portogallo',
                'langNL'=>'Portugal',
            ],
            [
                'id'=>624,
                'alpha2'=>'GW',
                'alpha3'=>'GNB',
                'langCS'=>'Guinea-Bissau',
                'lang_de'=>'Guinea-Bissau',
                'lang_en'=>'Guinea-Bissau',
                'langES'=>'Guinea-Bissau',
                'langFR'=>'Guinée-Bissau',
                'langIT'=>'Guinea-Bissau',
                'langNL'=>'Guinee-Bissau',
            ],
            [
                'id'=>626,
                'alpha2'=>'TL',
                'alpha3'=>'TLS',
                'langCS'=>'Východní Timor',
                'lang_de'=>'Timor-Leste',
                'lang_en'=>'Timor-Leste',
                'langES'=>'Timor Leste',
                'langFR'=>'Timor-Leste',
                'langIT'=>'Timor Est',
                'langNL'=>'Oost-Timor',
            ],
            [
                'id'=>630,
                'alpha2'=>'PR',
                'alpha3'=>'PRI',
                'langCS'=>'Portoriko',
                'lang_de'=>'Puerto Rico',
                'lang_en'=>'Puerto Rico',
                'langES'=>'Puerto Rico',
                'langFR'=>'Porto Rico',
                'langIT'=>'Porto Rico',
                'langNL'=>'Puerto Rico',
            ],
            [
                'id'=>634,
                'alpha2'=>'QA',
                'alpha3'=>'QAT',
                'langCS'=>'Katar',
                'lang_de'=>'Katar',
                'lang_en'=>'Qatar',
                'langES'=>'Qatar',
                'langFR'=>'Qatar',
                'langIT'=>'Qatar',
                'langNL'=>'Qatar',
            ],
            [
                'id'=>638,
                'alpha2'=>'RE',
                'alpha3'=>'REU',
                'langCS'=>'Reunion',
                'lang_de'=>'Réunion',
                'lang_en'=>'Réunion',
                'langES'=>'Reunión',
                'langFR'=>'Réunion',
                'langIT'=>'Reunion',
                'langNL'=>'Réunion',
            ],
            [
                'id'=>642,
                'alpha2'=>'RO',
                'alpha3'=>'ROU',
                'langCS'=>'Rumunsko',
                'lang_de'=>'Rumänien',
                'lang_en'=>'Romania',
                'langES'=>'Rumanía',
                'langFR'=>'Roumanie',
                'langIT'=>'Romania',
                'langNL'=>'Roemenië',
            ],
            [
                'id'=>643,
                'alpha2'=>'RU',
                'alpha3'=>'RUS',
                'langCS'=>'Rusko',
                'lang_de'=>'Russische Föderation',
                'lang_en'=>'Russian Federation',
                'langES'=>'Rusia',
                'langFR'=>'Fédération de Russie',
                'langIT'=>'Federazione Russa',
                'langNL'=>'Rusland',
            ],
            [
                'id'=>646,
                'alpha2'=>'RW',
                'alpha3'=>'RWA',
                'langCS'=>'Rwanda',
                'lang_de'=>'Ruanda',
                'lang_en'=>'Rwanda',
                'langES'=>'Ruanda',
                'langFR'=>'Rwanda',
                'langIT'=>'Ruanda',
                'langNL'=>'Rwanda',
            ],
            [
                'id'=>654,
                'alpha2'=>'SH',
                'alpha3'=>'SHN',
                'langCS'=>'Svatá Helena',
                'lang_de'=>'St. Helena',
                'lang_en'=>'Saint Helena',
                'langES'=>'Santa Helena',
                'langFR'=>'Sainte-Hélène',
                'langIT'=>'Sant',
                'langNL'=>'Elena',
            ],
            [
                'id'=>659,
                'alpha2'=>'KN',
                'alpha3'=>'KNA',
                'langCS'=>'Svatý Kitts a Nevis',
                'lang_de'=>'St. Kitts und Nevis',
                'lang_en'=>'Saint Kitts and Nevis',
                'langES'=>'Santa Kitts y Nevis',
                'langFR'=>'Saint-Kitts-et-Nevis',
                'langIT'=>'Saint Kitts e Nevis',
                'langNL'=>'Saint Kitts en Nevis',
            ],
            [
                'id'=>660,
                'alpha2'=>'AI',
                'alpha3'=>'AIA',
                'langCS'=>'Anguilla',
                'lang_de'=>'Anguilla',
                'lang_en'=>'Anguilla',
                'langES'=>'Anguilla',
                'langFR'=>'Anguilla',
                'langIT'=>'Anguilla',
                'langNL'=>'Anguilla',
            ],
            [
                'id'=>662,
                'alpha2'=>'LC',
                'alpha3'=>'LCA',
                'langCS'=>'Svatá Lucie',
                'lang_de'=>'St. Lucia',
                'lang_en'=>'Saint Lucia',
                'langES'=>'Santa Lucía',
                'langFR'=>'Sainte-Lucie',
                'langIT'=>'Santa Lucia',
                'langNL'=>'Saint Lucia',
            ],
            [
                'id'=>666,
                'alpha2'=>'PM',
                'alpha3'=>'SPM',
                'langCS'=>'Svatý Pierre a Miquelon',
                'lang_de'=>'St. Pierre und Miquelon',
                'lang_en'=>'Saint-Pierre and Miquelon',
                'langES'=>'San Pedro y Miquelon',
                'langFR'=>'Saint-Pierre-et-Miquelon',
                'langIT'=>'Saint Pierre e Miquelon',
                'langNL'=>'Saint-Pierre en Miquelon',
            ],
            [
                'id'=>670,
                'alpha2'=>'VC',
                'alpha3'=>'VCT',
                'langCS'=>'Svatý Vincenc a Grenadiny',
                'lang_de'=>'St. Vincent und die Grenadinen',
                'lang_en'=>'Saint Vincent and the Grenadines',
                'langES'=>'San Vincente y Las Granadinas',
                'langFR'=>'Saint-Vincent-et-les Grenadines',
                'langIT'=>'Saint Vincent e Grenadine',
                'langNL'=>'Saint Vincent en de Grenadines',
            ],
            [
                'id'=>674,
                'alpha2'=>'SM',
                'alpha3'=>'SMR',
                'langCS'=>'San Marino',
                'lang_de'=>'San Marino',
                'lang_en'=>'San Marino',
                'langES'=>'San Marino',
                'langFR'=>'Saint-Marin',
                'langIT'=>'San Marino',
                'langNL'=>'San Marino',
            ],
            [
                'id'=>678,
                'alpha2'=>'ST',
                'alpha3'=>'STP',
                'langCS'=>'Svatý Tomáš a Princův ostrov',
                'lang_de'=>'São Tomé und Príncipe',
                'lang_en'=>'Sao Tome and Principe',
                'langES'=>'Santo Tomé y Príncipe',
                'langFR'=>'Sao Tomé-et-Principe',
                'langIT'=>'Sao Tome e Principe',
                'langNL'=>'Sao Tomé en Principe',
            ],
            [
                'id'=>682,
                'alpha2'=>'SA',
                'alpha3'=>'SAU',
                'langCS'=>'Saudská Arábie',
                'lang_de'=>'Saudi-Arabien',
                'lang_en'=>'Saudi Arabia',
                'langES'=>'Arabia Saudí',
                'langFR'=>'Arabie Saoudite',
                'langIT'=>'Arabia Saudita',
                'langNL'=>'Saoedi-Arabië',
            ],
            [
                'id'=>686,
                'alpha2'=>'SN',
                'alpha3'=>'SEN',
                'langCS'=>'Senegal',
                'lang_de'=>'Senegal',
                'lang_en'=>'Senegal',
                'langES'=>'Senegal',
                'langFR'=>'Sénégal',
                'langIT'=>'Senegal',
                'langNL'=>'Senegal',
            ],
            [
                'id'=>690,
                'alpha2'=>'SC',
                'alpha3'=>'SYC',
                'langCS'=>'Seychely',
                'lang_de'=>'Seychellen',
                'lang_en'=>'Seychelles',
                'langES'=>'Seychelles',
                'langFR'=>'Seychelles',
                'langIT'=>'Seychelles',
                'langNL'=>'Seychellen',
            ],
            [
                'id'=>694,
                'alpha2'=>'SL',
                'alpha3'=>'SLE',
                'langCS'=>'Sierra Leone',
                'lang_de'=>'Sierra Leone',
                'lang_en'=>'Sierra Leone',
                'langES'=>'Sierra Leona',
                'langFR'=>'Sierra Leone',
                'langIT'=>'Sierra Leone',
                'langNL'=>'Sierra Leone',
            ],
            [
                'id'=>702,
                'alpha2'=>'SG',
                'alpha3'=>'SGP',
                'langCS'=>'Singapur',
                'lang_de'=>'Singapur',
                'lang_en'=>'Singapore',
                'langES'=>'Singapur',
                'langFR'=>'Singapour',
                'langIT'=>'Singapore',
                'langNL'=>'Singapore',
            ],
            [
                'id'=>703,
                'alpha2'=>'SK',
                'alpha3'=>'SVK',
                'langCS'=>'Slovensko',
                'lang_de'=>'Slowakei',
                'lang_en'=>'Slovakia',
                'langES'=>'Eslovaquia',
                'langFR'=>'Slovaquie',
                'langIT'=>'Slovacchia',
                'langNL'=>'Slowakije',
            ],
            [
                'id'=>704,
                'alpha2'=>'VN',
                'alpha3'=>'VNM',
                'langCS'=>'Vietnam',
                'lang_de'=>'Vietnam',
                'lang_en'=>'Vietnam',
                'langES'=>'Vietnam',
                'langFR'=>'Viet Nam',
                'langIT'=>'Vietnam',
                'langNL'=>'Vietnam',
            ],
            [
                'id'=>705,
                'alpha2'=>'SI',
                'alpha3'=>'SVN',
                'langCS'=>'Slovinsko',
                'lang_de'=>'Slowenien',
                'lang_en'=>'Slovenia',
                'langES'=>'Eslovenia',
                'langFR'=>'Slovénie',
                'langIT'=>'Slovenia',
                'langNL'=>'Slovenië',
            ],
            [
                'id'=>706,
                'alpha2'=>'SO',
                'alpha3'=>'SOM',
                'langCS'=>'Somálsko',
                'lang_de'=>'Somalia',
                'lang_en'=>'Somalia',
                'langES'=>'Somalia',
                'langFR'=>'Somalie',
                'langIT'=>'Somalia',
                'langNL'=>'Somalië',
            ],
            [
                'id'=>710,
                'alpha2'=>'ZA',
                'alpha3'=>'ZAF',
                'langCS'=>'Jižní Afrika',
                'lang_de'=>'Südafrika',
                'lang_en'=>'South Africa',
                'langES'=>'Sudáfrica',
                'langFR'=>'Afrique du Sud',
                'langIT'=>'Sud Africa',
                'langNL'=>'Zuid-Afrika',
            ],
            [
                'id'=>716,
                'alpha2'=>'ZW',
                'alpha3'=>'ZWE',
                'langCS'=>'Zimbabwe',
                'lang_de'=>'Simbabwe',
                'lang_en'=>'Zimbabwe',
                'langES'=>'Zimbabue',
                'langFR'=>'Zimbabwe',
                'langIT'=>'Zimbabwe',
                'langNL'=>'Zimbabwe',
            ],
            [
                'id'=>724,
                'alpha2'=>'ES',
                'alpha3'=>'ESP',
                'langCS'=>'Španělsko',
                'lang_de'=>'Spanien',
                'lang_en'=>'Spain',
                'langES'=>'España',
                'langFR'=>'Espagne',
                'langIT'=>'Spagna',
                'langNL'=>'Spanje',
            ],
            [
                'id'=>732,
                'alpha2'=>'EH',
                'alpha3'=>'ESH',
                'langCS'=>'Západní Sahara',
                'lang_de'=>'Westsahara',
                'lang_en'=>'Western Sahara',
                'langES'=>'Sáhara Occidental',
                'langFR'=>'Sahara Occidental',
                'langIT'=>'Sahara Occidentale',
                'langNL'=>'Westelijke Sahara',
            ],
            [
                'id'=>736,
                'alpha2'=>'SD',
                'alpha3'=>'SDN',
                'langCS'=>'Súdán',
                'lang_de'=>'Sudan',
                'lang_en'=>'Sudan',
                'langES'=>'Sudán',
                'langFR'=>'Soudan',
                'langIT'=>'Sudan',
                'langNL'=>'Sudan',
            ],
            [
                'id'=>738,
                'alpha2'=>'SS',
                'alpha3'=>'SSD',
                'langCS'=>'Jižní Súdán',
                'lang_de'=>'Südsudan',
                'lang_en'=>'South Sudan',
                'langES'=>'Sudán del Sur',
                'langFR'=>'Soudan du Sud',
                'langIT'=>'Sudan del Sud',
                'langNL'=>'Zuid-Soedan',
            ],
            [
                'id'=>740,
                'alpha2'=>'SR',
                'alpha3'=>'SUR',
                'langCS'=>'Surinam',
                'lang_de'=>'Suriname',
                'lang_en'=>'Suriname',
                'langES'=>'Surinám',
                'langFR'=>'Suriname',
                'langIT'=>'Suriname',
                'langNL'=>'Suriname',
            ],
            [
                'id'=>744,
                'alpha2'=>'SJ',
                'alpha3'=>'SJM',
                'langCS'=>'Špicberky a Jan Mayen',
                'lang_de'=>'Svalbard and Jan Mayen',
                'lang_en'=>'Svalbard and Jan Mayen',
                'langES'=>'Esvalbard y Jan Mayen',
                'langFR'=>'Svalbard etÎle Jan Mayen',
                'langIT'=>'Svalbard e Jan Mayen',
                'langNL'=>'Svalbard',
            ],
            [
                'id'=>748,
                'alpha2'=>'SZ',
                'alpha3'=>'SWZ',
                'langCS'=>'Svazijsko',
                'lang_de'=>'Swasiland',
                'lang_en'=>'Swaziland',
                'langES'=>'Suazilandia',
                'langFR'=>'Swaziland',
                'langIT'=>'Swaziland',
                'langNL'=>'Swaziland',
            ],
            [
                'id'=>752,
                'alpha2'=>'SE',
                'alpha3'=>'SWE',
                'langCS'=>'Švédsko',
                'lang_de'=>'Schweden',
                'lang_en'=>'Sweden',
                'langES'=>'Suecia',
                'langFR'=>'Suède',
                'langIT'=>'Svezia',
                'langNL'=>'Zweden',
            ],
            [
                'id'=>756,
                'alpha2'=>'CH',
                'alpha3'=>'CHE',
                'langCS'=>'Švýcarsko',
                'lang_de'=>'Schweiz',
                'lang_en'=>'Switzerland',
                'langES'=>'Suiza',
                'langFR'=>'Suisse',
                'langIT'=>'Svizzera',
                'langNL'=>'Zwitserland',
            ],
            [
                'id'=>760,
                'alpha2'=>'SY',
                'alpha3'=>'SYR',
                'langCS'=>'Sýrie',
                'lang_de'=>'Arabische Republik Syrien',
                'lang_en'=>'Syrian Arab Republic',
                'langES'=>'Siria',
                'langFR'=>'République Arabe Syrienne',
                'langIT'=>'Siria',
                'langNL'=>'Syrië',
            ],
            [
                'id'=>762,
                'alpha2'=>'TJ',
                'alpha3'=>'TJK',
                'langCS'=>'Tadžikistán',
                'lang_de'=>'Tadschikistan',
                'lang_en'=>'Tajikistan',
                'langES'=>'Tajikistán',
                'langFR'=>'Tadjikistan',
                'langIT'=>'Tagikistan',
                'langNL'=>'Tadzjikistan',
            ],
            [
                'id'=>764,
                'alpha2'=>'TH',
                'alpha3'=>'THA',
                'langCS'=>'Thajsko',
                'lang_de'=>'Thailand',
                'lang_en'=>'Thailand',
                'langES'=>'Tailandia',
                'langFR'=>'Thaïlande',
                'langIT'=>'Tailandia',
                'langNL'=>'Thailand',
            ],
            [
                'id'=>768,
                'alpha2'=>'TG',
                'alpha3'=>'TGO',
                'langCS'=>'Togo',
                'lang_de'=>'Togo',
                'lang_en'=>'Togo',
                'langES'=>'Togo',
                'langFR'=>'Togo',
                'langIT'=>'Togo',
                'langNL'=>'Togo',
            ],
            [
                'id'=>772,
                'alpha2'=>'TK',
                'alpha3'=>'TKL',
                'langCS'=>'Tokelau',
                'lang_de'=>'Tokelau',
                'lang_en'=>'Tokelau',
                'langES'=>'Tokelau',
                'langFR'=>'Tokelau',
                'langIT'=>'Tokelau',
                'langNL'=>'Tokelau -eilanden',
            ],
            [
                'id'=>776,
                'alpha2'=>'TO',
                'alpha3'=>'TON',
                'langCS'=>'Tonga',
                'lang_de'=>'Tonga',
                'lang_en'=>'Tonga',
                'langES'=>'Tongo',
                'langFR'=>'Tonga',
                'langIT'=>'Tonga',
                'langNL'=>'Tonga',
            ],
            [
                'id'=>780,
                'alpha2'=>'TT',
                'alpha3'=>'TTO',
                'langCS'=>'Trinidad a Tobago',
                'lang_de'=>'Trinidad und Tobago',
                'lang_en'=>'Trinidad and Tobago',
                'langES'=>'Trinidad y Tobago',
                'langFR'=>'Trinité-et-Tobago',
                'langIT'=>'Trinidad e Tobago',
                'langNL'=>'Trinidad en Tobago',
            ],
            [
                'id'=>784,
                'alpha2'=>'AE',
                'alpha3'=>'ARE',
                'langCS'=>'Spojené Arabské Emiráty',
                'lang_de'=>'Vereinigte Arabische Emirate',
                'lang_en'=>'United Arab Emirates',
                'langES'=>'EmiratosÁrabes Unidos',
                'langFR'=>'Émirats Arabes Unis',
                'langIT'=>'Emirati Arabi Uniti',
                'langNL'=>'Verenigde Arabische Emiraten',
            ],
            [
                'id'=>788,
                'alpha2'=>'TN',
                'alpha3'=>'TUN',
                'langCS'=>'Tunisko',
                'lang_de'=>'Tunesien',
                'lang_en'=>'Tunisia',
                'langES'=>'Túnez',
                'langFR'=>'Tunisie',
                'langIT'=>'Tunisia',
                'langNL'=>'Tunesië',
            ],
            [
                'id'=>792,
                'alpha2'=>'TR',
                'alpha3'=>'TUR',
                'langCS'=>'Turecko',
                'lang_de'=>'Türkei',
                'lang_en'=>'Turkey',
                'langES'=>'Turquía',
                'langFR'=>'Turquie',
                'langIT'=>'Turchia',
                'langNL'=>'Turkije',
            ],
            [
                'id'=>795,
                'alpha2'=>'TM',
                'alpha3'=>'TKM',
                'langCS'=>'Turkmenistán',
                'lang_de'=>'Turkmenistan',
                'lang_en'=>'Turkmenistan',
                'langES'=>'Turmenistán',
                'langFR'=>'Turkménistan',
                'langIT'=>'Turkmenistan',
                'langNL'=>'Turkmenistan',
            ],
            [
                'id'=>796,
                'alpha2'=>'TC',
                'alpha3'=>'TCA',
                'langCS'=>'Turks a ostrovy Caicos',
                'lang_de'=>'Turks- und Caicosinseln',
                'lang_en'=>'Turks and Caicos Islands',
                'langES'=>'Islas Turks y Caicos',
                'langFR'=>'Îles Turks et Caïques',
                'langIT'=>'Isole Turks e Caicos',
                'langNL'=>'Turks- en Caicoseilanden',
            ],
            [
                'id'=>798,
                'alpha2'=>'TV',
                'alpha3'=>'TUV',
                'langCS'=>'Tuvalu',
                'lang_de'=>'Tuvalu',
                'lang_en'=>'Tuvalu',
                'langES'=>'Tuvalu',
                'langFR'=>'Tuvalu',
                'langIT'=>'Tuvalu',
                'langNL'=>'Tuvalu',
            ],
            [
                'id'=>800,
                'alpha2'=>'UG',
                'alpha3'=>'UGA',
                'langCS'=>'Uganda',
                'lang_de'=>'Uganda',
                'lang_en'=>'Uganda',
                'langES'=>'Uganda',
                'langFR'=>'Ouganda',
                'langIT'=>'Uganda',
                'langNL'=>'Oeganda',
            ],
            [
                'id'=>804,
                'alpha2'=>'UA',
                'alpha3'=>'UKR',
                'langCS'=>'Ukrajina',
                'lang_de'=>'Ukraine',
                'lang_en'=>'Ukraine',
                'langES'=>'Ucrania',
                'langFR'=>'Ukraine',
                'langIT'=>'Ucraina',
                'langNL'=>'Oekraïne',
            ],
            [
                'id'=>807,
                'alpha2'=>'MK',
                'alpha3'=>'MKD',
                'langCS'=>'Makedonie',
                'lang_de'=>'Ehem. jugoslawische Republik Mazedonien',
                'lang_en'=>'The Former Yugoslav Republic of Macedonia',
                'langES'=>'Macedonia',
                'langFR'=>'L',
                'langIT'=>'ex-République Yougoslave de Macédoine',
                'langNL'=>'Macedonia',
            ],
            [
                'id'=>818,
                'alpha2'=>'EG',
                'alpha3'=>'EGY',
                'langCS'=>'Egypt',
                'lang_de'=>'Ägypten',
                'lang_en'=>'Egypt',
                'langES'=>'Egipto',
                'langFR'=>'Égypte',
                'langIT'=>'Egitto',
                'langNL'=>'Egypte',
            ],
            [
                'id'=>826,
                'alpha2'=>'GB',
                'alpha3'=>'GBR',
                'langCS'=>'Velká Británie',
                'lang_de'=>'Vereinigtes Königreich von Großbritannien und',
                'lang_en'=>'United Kingdom',
                'langES'=>'Reino Unido',
                'langFR'=>'Royaume-Uni',
                'langIT'=>'Regno Unito',
                'langNL'=>'Verenigd Koninkrijk',
            ],
            [
                'id'=>833,
                'alpha2'=>'IM',
                'alpha3'=>'IMN',
                'langCS'=>'Ostrov Man',
                'lang_de'=>'Insel Man',
                'lang_en'=>'Isle of Man',
                'langES'=>'Isla de Man',
                'langFR'=>'Île de Man',
                'langIT'=>'Isola di Man',
                'langNL'=>'Eiland Man',
            ],
            [
                'id'=>834,
                'alpha2'=>'TZ',
                'alpha3'=>'TZA',
                'langCS'=>'Tanzánie',
                'lang_de'=>'Vereinigte Republik Tansania',
                'lang_en'=>'United Republic Of Tanzania',
                'langES'=>'Tanzania',
                'langFR'=>'République-Unie de Tanzanie',
                'langIT'=>'Tanzania',
                'langNL'=>'Tanzania',
            ],
            [
                'id'=>840,
                'alpha2'=>'US',
                'alpha3'=>'USA',
                'langCS'=>'USA',
                'lang_de'=>'Vereinigte Staaten von Amerika',
                'lang_en'=>'United States',
                'langES'=>'Estados Unidos',
                'langFR'=>'États-Unis',
                'langIT'=>'Stati Uniti de America',
                'langNL'=>' Verenigde Staten',
            ],
            [
                'id'=>850,
                'alpha2'=>'VI',
                'alpha3'=>'VIR',
                'langCS'=>'Americké Panenské ostrovy',
                'lang_de'=>'Amerikanische Jungferninseln',
                'lang_en'=>'U.S. Virgin Islands',
                'langES'=>'Islas Vírgenes Estadounidenses',
                'langFR'=>'Îles Vierges des États-Unis',
                'langIT'=>'Isole Vergini Americane',
                'langNL'=>'Amerikaanse Maagdeneilanden',
            ],
            [
                'id'=>854,
                'alpha2'=>'BF',
                'alpha3'=>'BFA',
                'langCS'=>'Burkina Faso',
                'lang_de'=>'Burkina Faso',
                'lang_en'=>'Burkina Faso',
                'langES'=>'Burkina Faso',
                'langFR'=>'Burkina Faso',
                'langIT'=>'Burkina Faso',
                'langNL'=>'Burkina Faso',
            ],
            [
                'id'=>858,
                'alpha2'=>'UY',
                'alpha3'=>'URY',
                'langCS'=>'Uruguay',
                'lang_de'=>'Uruguay',
                'lang_en'=>'Uruguay',
                'langES'=>'Uruguay',
                'langFR'=>'Uruguay',
                'langIT'=>'Uruguay',
                'langNL'=>'Uruguay',
            ],
            [
                'id'=>860,
                'alpha2'=>'UZ',
                'alpha3'=>'UZB',
                'langCS'=>'Uzbekistán',
                'lang_de'=>'Usbekistan',
                'lang_en'=>'Uzbekistan',
                'langES'=>'Uzbekistán',
                'langFR'=>'Ouzbékistan',
                'langIT'=>'Uzbekistan',
                'langNL'=>'Oezbekistan',
            ],
            [
                'id'=>862,
                'alpha2'=>'VE',
                'alpha3'=>'VEN',
                'langCS'=>'Venezuela',
                'lang_de'=>'Venezuela',
                'lang_en'=>'Venezuela',
                'langES'=>'Venezuela',
                'langFR'=>'Venezuela',
                'langIT'=>'Venezuela',
                'langNL'=>'Venezuela',
            ],
            [
                'id'=>876,
                'alpha2'=>'WF',
                'alpha3'=>'WLF',
                'langCS'=>'Wallis a Futuna',
                'lang_de'=>'Wallis und Futuna',
                'lang_en'=>'Wallis and Futuna',
                'langES'=>'Wallis y Futuna',
                'langFR'=>'Wallis et Futuna',
                'langIT'=>'Wallis e Futuna',
                'langNL'=>'Wallis en Futuna',
            ],
            [
                'id'=>882,
                'alpha2'=>'WS',
                'alpha3'=>'WSM',
                'langCS'=>'Samoa',
                'lang_de'=>'Samoa',
                'lang_en'=>'Samoa',
                'langES'=>'Samoa',
                'langFR'=>'Samoa',
                'langIT'=>'Samoa',
                'langNL'=>'Samoa',
            ],
            [
                'id'=>887,
                'alpha2'=>'YE',
                'alpha3'=>'YEM',
                'langCS'=>'Jemen',
                'lang_de'=>'Jemen',
                'lang_en'=>'Yemen',
                'langES'=>'Yemen',
                'langFR'=>'Yémen',
                'langIT'=>'Yemen',
                'langNL'=>'Jemen',
            ],
            [
                'id'=>891,
                'alpha2'=>'CS',
                'alpha3'=>'SCG',
                'langCS'=>'Serbia and Montenegro',
                'lang_de'=>'Serbien und Montenegro',
                'lang_en'=>'Serbia and Montenegro',
                'langES'=>'Serbia y Montenegro',
                'langFR'=>'Serbie-et-Monténégro',
                'langIT'=>'Serbia e Montenegro',
                'langNL'=>'Servië en Montenegro',
            ],
            [
                'id'=>894,
                'alpha2'=>'ZM',
                'alpha3'=>'ZMB',
                'langCS'=>'Zambie',
                'lang_de'=>'Sambia',
                'lang_en'=>'Zambia',
                'langES'=>'Zambia',
                'langFR'=>'Zambie',
                'langIT'=>'Zambia',
                'langNL'=>'Zambia',
            ],
        ];
        Country::insert($countries);
    }
}
