<?php

namespace Database\Seeders;

use App\Subject;
use Illuminate\Database\Seeder;

class SubjectsTableSeeder extends Seeder
{
    public function run()
    {
        $subjects = [[
            'id' => 1,
            'title' => 'Katholische Religionslehre',
            'external_id' => 1,
            'organization_type_id' => 1,
        ],
            [
                'id' => 2,
                'title' => 'Evangelische Religionslehre',
                'external_id' => 2,
                'organization_type_id' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Ethikunterricht',
                'external_id' => 3,
                'organization_type_id' => 1,
            ],
            [
                'id' => 4,
                'title' => 'Deutsch',
                'external_id' => 4,
                'organization_type_id' => 1,
            ],
            [
                'id' => 5,
                'title' => 'Deutsch für Schüler-/innen mit nicht ausreichenden Deutschkenntnissen (Deutsch als Zweitsprache)',
                'external_id' => 6,
                'organization_type_id' => 1,
            ],
            [
                'id' => 6,
                'title' => 'Englisch',
                'external_id' => 7,
                'organization_type_id' => 1,
            ],
            [
                'id' => 7,
                'title' => 'Französisch',
                'external_id' => 8,
                'organization_type_id' => 1,
            ],
            [
                'id' => 8,
                'title' => 'Latein',
                'external_id' => 9,
                'organization_type_id' => 1,
            ],
            [
                'id' => 9,
                'title' => 'Albanisch',
                'external_id' => 10,
                'organization_type_id' => 1,
            ],
            [
                'id' => 10,
                'title' => 'Arabisch',
                'external_id' => 11,
                'organization_type_id' => 1,
            ],
            [
                'id' => 11,
                'title' => 'Bosnisch',
                'external_id' => 12,
                'organization_type_id' => 1,
            ],
            [
                'id' => 12,
                'title' => 'Chinesisch',
                'external_id' => 13,
                'organization_type_id' => 1,
            ],
            [
                'id' => 13,
                'title' => 'Griechisch',
                'external_id' => 14,
                'organization_type_id' => 1,
            ],
            [
                'id' => 14,
                'title' => 'Hebräisch',
                'external_id' => 16,
                'organization_type_id' => 1,
            ],
            [
                'id' => 15,
                'title' => 'Italienisch',
                'external_id' => 17,
                'organization_type_id' => 1,
            ],
            [
                'id' => 16,
                'title' => 'Japanisch',
                'external_id' => 18,
                'organization_type_id' => 1,
            ],
            [
                'id' => 17,
                'title' => 'Kroatisch',
                'external_id' => 19,
                'organization_type_id' => 1,
            ],
            [
                'id' => 18,
                'title' => 'Polnisch',
                'external_id' => 22,
                'organization_type_id' => 1,
            ],
            [
                'id' => 19,
                'title' => 'Portugiesisch',
                'external_id' => 23,
                'organization_type_id' => 1,
            ],
            [
                'id' => 20,
                'title' => 'Russisch',
                'external_id' => 25,
                'organization_type_id' => 1,
            ],
            [
                'id' => 21,
                'title' => 'Schwedisch',
                'external_id' => 26,
                'organization_type_id' => 1,
            ],
            [
                'id' => 22,
                'title' => 'Serbisch',
                'external_id' => 27,
                'organization_type_id' => 1,
            ],
            [
                'id' => 23,
                'title' => 'Slowenisch',
                'external_id' => 29,
                'organization_type_id' => 1,
            ],
            [
                'id' => 24,
                'title' => 'Spanisch',
                'external_id' => 30,
                'organization_type_id' => 1,
            ],
            [
                'id' => 25,
                'title' => 'Türkisch',
                'external_id' => 31,
                'organization_type_id' => 1,
            ],
            [
                'id' => 26,
                'title' => 'Fremdsprachen',
                'external_id' => 32,
                'organization_type_id' => 1,
            ],
            [
                'id' => 27,
                'title' => 'Herkunftssprache',
                'external_id' => 32,
                'organization_type_id' => 1,
            ],
            [
                'id' => 28,
                'title' => 'Sonstige Fremdsprache / Herkunftssprache',
                'external_id' => 32,
                'organization_type_id' => 1,
            ],
            [
                'id' => 29,
                'title' => 'Erdkunde / Geographie / Wirtschgeographie',
                'external_id' => 33,
                'organization_type_id' => 1,
            ],
            [
                'id' => 30,
                'title' => 'Geographie',
                'external_id' => 33,
                'organization_type_id' => 1,
            ],
            [
                'id' => 31,
                'title' => 'Wirtschaftsgeographie',
                'external_id' => 33,
                'organization_type_id' => 1,
            ],
            [
                'id' => 32,
                'title' => 'Erdkunde in englischer Sprache',
                'external_id' => 34,
                'organization_type_id' => 1,
            ],
            [
                'id' => 33,
                'title' => 'Erdkunde in französischer Sprache',
                'external_id' => 35,
                'organization_type_id' => 1,
            ],
            [
                'id' => 34,
                'title' => 'Gemeinschaftskunde',
                'external_id' => 36,
                'organization_type_id' => 1,
            ],
            [
                'id' => 35,
                'title' => 'Gesellschaftswissenschaft(liche Fächer)',
                'external_id' => 36,
                'organization_type_id' => 1,
            ],
            [
                'id' => 36,
                'title' => 'Gemeinschaftskunde in englischer Sprache',
                'external_id' => 37,
                'organization_type_id' => 1,
            ],
            [
                'id' => 37,
                'title' => 'Gesellschaftswissenschaft(liche Fächer) in englischer Sprache',
                'external_id' => 37,
                'organization_type_id' => 1,
            ],
            [
                'id' => 38,
                'title' => 'Gemeinschaftskunde in französischer Sprache',
                'external_id' => 38,
                'organization_type_id' => 1,
            ],
            [
                'id' => 39,
                'title' => 'Gesellschaftswissenschaft(liche Fächer) in französischer Sprache',
                'external_id' => 38,
                'organization_type_id' => 1,
            ],
            [
                'id' => 40,
                'title' => 'Geschichte',
                'external_id' => 39,
                'organization_type_id' => 1,
            ],
            [
                'id' => 41,
                'title' => 'Geschichte in englischer Sprache',
                'external_id' => 40,
                'organization_type_id' => 1,
            ],
            [
                'id' => 42,
                'title' => 'Geschichte in französischer Sprache',
                'external_id' => 41,
                'organization_type_id' => 1,
            ],
            [
                'id' => 43,
                'title' => 'Sozialkunde (auch: Politikwissenschaft)',
                'external_id' => 42,
                'organization_type_id' => 1,
            ],
            [
                'id' => 44,
                'title' => 'Politikwissenschaft in englischer Sprache',
                'external_id' => 43,
                'organization_type_id' => 1,
            ],
            [
                'id' => 45,
                'title' => 'Sozialkunde in englischer Sprache',
                'external_id' => 43,
                'organization_type_id' => 1,
            ],
            [
                'id' => 46,
                'title' => 'Politikwissenschaft in französischer Sprache',
                'external_id' => 44,
                'organization_type_id' => 1,
            ],
            [
                'id' => 47,
                'title' => 'Sozialkunde in französischer Sprache',
                'external_id' => 44,
                'organization_type_id' => 1,
            ],
            [
                'id' => 48,
                'title' => 'Gesellschaftslehre',
                'external_id' => 46,
                'organization_type_id' => 1,
            ],
            [
                'id' => 49,
                'title' => 'Biologie',
                'external_id' => 48,
                'organization_type_id' => 1,
            ],
            [
                'id' => 50,
                'title' => 'Chemie',
                'external_id' => 49,
                'organization_type_id' => 1,
            ],
            [
                'id' => 51,
                'title' => 'Mathematik',
                'external_id' => 50,
                'organization_type_id' => 1,
            ],
            [
                'id' => 52,
                'title' => 'Mathematik / Naturwissenschaften',
                'external_id' => 51,
                'organization_type_id' => 1,
            ],
            [
                'id' => 53,
                'title' => 'Physik',
                'external_id' => 52,
                'organization_type_id' => 1,
            ],
            [
                'id' => 54,
                'title' => 'Physik / Chemie',
                'external_id' => 53,
                'organization_type_id' => 1,
            ],
            [
                'id' => 55,
                'title' => 'Physik / Chemie / Biologie',
                'external_id' => 54,
                'organization_type_id' => 1,
            ],
            [
                'id' => 56,
                'title' => 'Naturwissenschaftlicher Bereich',
                'external_id' => 55,
                'organization_type_id' => 1,
            ],
            [
                'id' => 57,
                'title' => 'Bildende Kunst',
                'external_id' => 56,
                'organization_type_id' => 1,
            ],
            [
                'id' => 58,
                'title' => 'Bildende Kunst / Werken / Textiles Gestalten',
                'external_id' => 58,
                'organization_type_id' => 1,
            ],
            [
                'id' => 59,
                'title' => 'Musik (auch: Rhythmische Erziehung)',
                'external_id' => 59,
                'organization_type_id' => 1,
            ],
            [
                'id' => 60,
                'title' => 'Rhythmische Erziehung',
                'external_id' => 59,
                'organization_type_id' => 1,
            ],
            [
                'id' => 61,
                'title' => 'Chor',
                'external_id' => 60,
                'organization_type_id' => 1,
            ],
            [
                'id' => 62,
                'title' => 'Orchester',
                'external_id' => 61,
                'organization_type_id' => 1,
            ],
            [
                'id' => 63,
                'title' => 'Chor / Orchester',
                'external_id' => 62,
                'organization_type_id' => 1,
            ],
            [
                'id' => 64,
                'title' => 'Musik / Bildende Kunst',
                'external_id' => 63,
                'organization_type_id' => 1,
            ],
            [
                'id' => 65,
                'title' => 'Musisch-künstlerischer Bereich',
                'external_id' => 65,
                'organization_type_id' => 1,
            ],
            [
                'id' => 66,
                'title' => 'Textiles Gestalten',
                'external_id' => 66,
                'organization_type_id' => 1,
            ],
            [
                'id' => 67,
                'title' => 'Werken',
                'external_id' => 68,
                'organization_type_id' => 1,
            ],
            [
                'id' => 68,
                'title' => 'Arbeitslehre',
                'external_id' => 69,
                'organization_type_id' => 1,
            ],
            [
                'id' => 69,
                'title' => 'Blindenkurzschrift',
                'external_id' => 70,
                'organization_type_id' => 1,
            ],
            [
                'id' => 70,
                'title' => 'Bürowirtschaft / Textverarbeitung / Kurzschrift',
                'external_id' => 71,
                'organization_type_id' => 1,
            ],
            [
                'id' => 71,
                'title' => 'Textverarbeitung',
                'external_id' => 71,
                'organization_type_id' => 1,
            ],
            [
                'id' => 72,
                'title' => 'Datenverarbeitung / Wirtschaftsinformatik / Betriebsinformatik',
                'external_id' => 72,
                'organization_type_id' => 1,
            ],
            [
                'id' => 73,
                'title' => 'Familienhauswesen / Hauswirtschaft',
                'external_id' => 73,
                'organization_type_id' => 1,
            ],
            [
                'id' => 74,
                'title' => 'Informatik',
                'external_id' => 74,
                'organization_type_id' => 1,
            ],
            [
                'id' => 75,
                'title' => 'Philosophie',
                'external_id' => 77,
                'organization_type_id' => 1,
            ],
            [
                'id' => 76,
                'title' => 'Technisches Zeichnen',
                'external_id' => 78,
                'organization_type_id' => 1,
            ],
            [
                'id' => 77,
                'title' => 'Arbeitslehre: Wirtschafts- und Arbeitslehre Haushalt',
                'external_id' => 79,
                'organization_type_id' => 1,
            ],
            [
                'id' => 78,
                'title' => 'Wirtschafts- und Arbeitslehre Haushalt',
                'external_id' => 79,
                'organization_type_id' => 1,
            ],
            [
                'id' => 79,
                'title' => 'Arbeitslehre: Wirtschafts- und Arbeitslehre Technik / Technisches Werken',
                'external_id' => 80,
                'organization_type_id' => 1,
            ],
            [
                'id' => 80,
                'title' => 'Technisches Werken',
                'external_id' => 80,
                'organization_type_id' => 1,
            ],
            [
                'id' => 81,
                'title' => 'Wirtschafts- und Arbeitslehre Technik',
                'external_id' => 80,
                'organization_type_id' => 1,
            ],
            [
                'id' => 82,
                'title' => 'Wirtschaftskunde / Wirtschaftslehre / Wirtschafts- umd Sozialkunde',
                'external_id' => 81,
                'organization_type_id' => 1,
            ],
            [
                'id' => 83,
                'title' => 'Sportförderunterricht',
                'external_id' => 87,
                'organization_type_id' => 1,
            ],
            [
                'id' => 84,
                'title' => 'Hauswirtschaft und Sozialwesen',
                'external_id' => 91,
                'organization_type_id' => 1,
            ],
            [
                'id' => 85,
                'title' => 'Sozialwesen',
                'external_id' => 91,
                'organization_type_id' => 1,
            ],
            [
                'id' => 86,
                'title' => 'Technik und Naturwissenschaft',
                'external_id' => 92,
                'organization_type_id' => 1,
            ],
            [
                'id' => 87,
                'title' => 'Psychologie',
                'external_id' => 94,
                'organization_type_id' => 1,
            ],
            [
                'id' => 88,
                'title' => 'Sozialpädagogik',
                'external_id' => 98,
                'organization_type_id' => 1,
            ],
            [
                'id' => 89,
                'title' => 'Wirtschaft und Verwaltung',
                'external_id' => 102,
                'organization_type_id' => 1,
            ],
            [
                'id' => 90,
                'title' => 'Pädagogik',
                'external_id' => 156,
                'organization_type_id' => 1,
            ],
            [
                'id' => 91,
                'title' => 'LRS-Pädagogik',
                'external_id' => 157,
                'organization_type_id' => 1,
            ],
            [
                'id' => 92,
                'title' => 'Rahmenplan Grundschule',
                'external_id' => 161,
                'organization_type_id' => 1,
            ],
            [
                'id' => 93,
                'title' => 'Unterricht in der Primarstufe / Gesamtunterricht',
                'external_id' => 161,
                'organization_type_id' => 1,
            ],
            [
                'id' => 94,
                'title' => 'Sachunterricht / Sachkunde',
                'external_id' => 162,
                'organization_type_id' => 1,
            ],
            [
                'id' => 95,
                'title' => 'Klassenleiterstunde',
                'external_id' => 163,
                'organization_type_id' => 1,
            ],
            [
                'id' => 96,
                'title' => 'Freireligiöser Religionsunterricht',
                'external_id' => 167,
                'organization_type_id' => 1,
            ],
            [
                'id' => 97,
                'title' => 'Sonstiger Religionsunterricht',
                'external_id' => 167,
                'organization_type_id' => 1,
            ],
            [
                'id' => 98,
                'title' => 'Kultur (nur für G8-Gymnasien)',
                'external_id' => 168,
                'organization_type_id' => 1,
            ],
            [
                'id' => 99,
                'title' => 'Sonderpädagogischer Förderunterricht',
                'external_id' => 177,
                'organization_type_id' => 1,
            ],
            [
                'id' => 100,
                'title' => 'Unterricht in der Förderschule / Gesamtunterricht',
                'external_id' => 177,
                'organization_type_id' => 1,
            ],
            [
                'id' => 101,
                'title' => 'Niederländisch',
                'external_id' => 183,
                'organization_type_id' => 1,
            ],
            [
                'id' => 102,
                'title' => 'Eurythmie',
                'external_id' => 187,
                'organization_type_id' => 1,
            ],
            [
                'id' => 103,
                'title' => 'Darstellendes Spiel',
                'external_id' => 188,
                'organization_type_id' => 1,
            ],
            [
                'id' => 104,
                'title' => 'Jüdische Religionslehre',
                'external_id' => 195,
                'organization_type_id' => 1,
            ],
            [
                'id' => 105,
                'title' => 'Schulseelsorge',
                'external_id' => 196,
                'organization_type_id' => 1,
            ],
            [
                'id' => 106,
                'title' => 'Sport (ohne Schwimmen)',
                'external_id' => 197,
                'organization_type_id' => 1,
            ],
            [
                'id' => 107,
                'title' => 'Sport-Jungen (ohne Schwimmen)',
                'external_id' => 198,
                'organization_type_id' => 1,
            ],
            [
                'id' => 108,
                'title' => 'Sport-Mädchen (ohne Schwimmen)',
                'external_id' => 199,
                'organization_type_id' => 1,
            ],
            [
                'id' => 109,
                'title' => 'Sport-koedukativ (ohne Schwimmen)',
                'external_id' => 200,
                'organization_type_id' => 1,
            ],
            [
                'id' => 110,
                'title' => 'Schwimmen',
                'external_id' => 201,
                'organization_type_id' => 1,
            ],
            [
                'id' => 111,
                'title' => 'Schwimmen-Jungen',
                'external_id' => 202,
                'organization_type_id' => 1,
            ],
            [
                'id' => 112,
                'title' => 'Schwimmen-Mädchen',
                'external_id' => 203,
                'organization_type_id' => 1,
            ],
            [
                'id' => 113,
                'title' => 'Schwimmen-koedukativ',
                'external_id' => 204,
                'organization_type_id' => 1,
            ],
            [
                'id' => 114,
                'title' => 'Naturwissenschaften',
                'external_id' => 205,
                'organization_type_id' => 1,
            ],
            [
                'id' => 115,
                'title' => 'Islamische Religionslehre',
                'external_id' => 206,
                'organization_type_id' => 1,
            ],
            [
                'id' => 116,
                'title' => 'Verkehrserziehung',
                'external_id' => 994,
                'organization_type_id' => 1,
            ],
            [
                'id' => 117,
                'title' => 'Wahlpflichtbereich / Unterricht in der Sekundarstufe I',
                'external_id' => 995,
                'organization_type_id' => 1,
            ],
            [
                'id' => 118,
                'title' => 'Ökonomische Bildung',
                'external_id' => 996,
                'organization_type_id' => 1,
            ],
            [
                'id' => 119,
                'title' => 'Geschichte / Sozialkunde',
                'external_id' => 997,
                'organization_type_id' => 1,
            ],
            [
                'id' => 120,
                'title' => 'Freiwilliges 10. Schuljahr',
                'external_id' => 998,
                'organization_type_id' => 1,
            ],
            [
                'id' => 121,
                'title' => 'Berufsorientierung',
                'external_id' => 999,
                'organization_type_id' => 1,
            ],
        ];

        Subject::insert($subjects);
    }
}
