<?php

use App\Context;
use Illuminate\Database\Seeder;

class ContextsTableSeeder extends Seeder
{
    public function run()
    {
        $contexts = [
                    [
                    'id'=>1,
                    'title'=>'user',
                    'path'=>'users/'
                    ],			
                    [
                    'id'=>2,
                    'title'=>'curriculum',
                    'path'=>'curricula/'
                    ],			
                    [
                    'id'=>3,
                    'title'=>'avatar',
                    'path'=>'users/'
                    ],			
                    [
                    'id'=>4,
                    'title'=>'solution',
                    'path'=>'solutions/'
                    ],			
                    [
                    'id'=>5,
                    'title'=>'subject',
                    'path'=>'subjects/'
                    ],			
                    [
                    'id'=>6,
                    'title'=>'badge',
                    'path'=>'badges/'
                    ],			
                    [
                    'id'=>7,
                    'title'=>'editor',
                    'path'=>'user/'
                    ],			
                    [
                    'id'=>8,
                    'title'=>'backup',
                    'path'=>'backups/'
                    ],			
                    [
                    'id'=>9,
                    'title'=>'institution',
                    'path'=>'institution/'
                    ],			
                    [
                    'id'=>10,
                    'title'=>'coursebook',
                    'path'=>'coursebooks/'
                    ],			
                    [
                    'id'=>11,
                    'title'=>'dashboard',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>12,
                    'title'=>'enabling_objective',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>13,
                    'title'=>'task',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>14,
                    'title'=>'terms',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>15,
                    'title'=>'content',
                    'path'=>'curricula/'
                    ],			
                    [
                    'id'=>16,
                    'title'=>'group',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>17,
                    'title'=>'course',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>18,
                    'title'=>'wallet',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>19,
                    'title'=>'config',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>20,
                    'title'=>'signature',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>21,
                    'title'=>'blog',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>22,
                    'title'=>'user_certificate',
                    'path'=>'users/'
                    ],			
                    [
                    'id'=>23,
                    'title'=>'badge_preview',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>24,
                    'title'=>'license',
                    'path'=>'licenses/'
                    ],			
                    [
                    'id'=>25,
                    'title'=>'glossar',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>26,
                    'title'=>'reference',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>27,
                    'title'=>'terminal_objective',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>28,
                    'title'=>'navigator',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>29,
                    'title'=>'file',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>30,
                    'title'=>'navigator_view',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>31,
                    'title'=>'navigator_block',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>32,
                    'title'=>'debug',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>33,
                    'title'=>'book',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>34,
                    'title'=>'imprint',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>35,
                    'title'=>'privacy',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>36,
                    'title'=>'information',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>37,
                    'title'=>'print',
                    'path'=>NULL
                    ],			
                    [
                    'id'=>38,
                    'title'=>'accomplished',
                    'path'=>NULL
                    ]
            ];

        Context::insert($contexts);
    }
}
