<?php

use App\Country;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [[
                    'code'=>'AD',
                    'en'=>'Andorra',
                    'de'=>'Andorra',
                    'id'=>1
                    ],
                    [
                    'code'=>'AE',
                    'en'=>'United Arab Emirates',
                    'de'=>'Vereinigte Arabische Emirate',
                    'id'=>2
                    ],
                    [
                    'code'=>'AF',
                    'en'=>'Afghanistan',
                    'de'=>'Afghanistan',
                    'id'=>3
                    ],
                    [
                    'code'=>'AG',
                    'en'=>'Antigua and Barbuda',
                    'de'=>'Antigua und Barbuda',
                    'id'=>4
                    ],
                    [
                    'code'=>'AI',
                    'en'=>'Anguilla',
                    'de'=>'Anguilla',
                    'id'=>5
                    ],
                    [
                    'code'=>'AL',
                    'en'=>'Albania',
                    'de'=>'Albanien',
                    'id'=>6
                    ],
                    [
                    'code'=>'AM',
                    'en'=>'Armenia',
                    'de'=>'Armenien',
                    'id'=>7
                    ],
                    [
                    'code'=>'AN',
                    'en'=>'Netherlands Antilles',
                    'de'=>'Niederländische Antillen',
                    'id'=>8
                    ],
                    [
                    'code'=>'AO',
                    'en'=>'Angola',
                    'de'=>'Angola',
                    'id'=>9
                    ],
                    [
                    'code'=>'AQ',
                    'en'=>'Antarctica',
                    'de'=>'Antarktis',
                    'id'=>10
                    ],
                    [
                    'code'=>'AR',
                    'en'=>'Argentina',
                    'de'=>'Argentinien',
                    'id'=>11
                    ],
                    [
                    'code'=>'AS',
                    'en'=>'American Samoa',
                    'de'=>'Amerikanisch-Samoa',
                    'id'=>12
                    ],
                    [
                    'code'=>'AT',
                    'en'=>'Austria',
                    'de'=>'Österreich',
                    'id'=>13
                    ],
                    [
                    'code'=>'AU',
                    'en'=>'Australia',
                    'de'=>'Australien',
                    'id'=>14
                    ],
                    [
                    'code'=>'AW',
                    'en'=>'Aruba',
                    'de'=>'Aruba',
                    'id'=>15
                    ],
                    [
                    'code'=>'AX',
                    'en'=>'Aland Islands',
                    'de'=>'Aland',
                    'id'=>16
                    ],
                    [
                    'code'=>'AZ',
                    'en'=>'Azerbaijan',
                    'de'=>'Aserbaidschan',
                    'id'=>17
                    ],
                    [
                    'code'=>'BA',
                    'en'=>'Bosnia and Herzegovina',
                    'de'=>'Bosnien und Herzegowina',
                    'id'=>18
                    ],
                    [
                    'code'=>'BB',
                    'en'=>'Barbados',
                    'de'=>'Barbados',
                    'id'=>19
                    ],
                    [
                    'code'=>'BD',
                    'en'=>'Bangladesh',
                    'de'=>'Bangladesch',
                    'id'=>20
                    ],
                    [
                    'code'=>'BE',
                    'en'=>'Belgium',
                    'de'=>'Belgien',
                    'id'=>21
                    ],
                    [
                    'code'=>'BF',
                    'en'=>'Burkina Faso',
                    'de'=>'Burkina Faso',
                    'id'=>22
                    ],
                    [
                    'code'=>'BG',
                    'en'=>'Bulgaria',
                    'de'=>'Bulgarien',
                    'id'=>23
                    ],
                    [
                    'code'=>'BH',
                    'en'=>'Bahrain',
                    'de'=>'Bahrain',
                    'id'=>24
                    ],
                    [
                    'code'=>'BI',
                    'en'=>'Burundi',
                    'de'=>'Burundi',
                    'id'=>25
                    ],
                    [
                    'code'=>'BJ',
                    'en'=>'Benin',
                    'de'=>'Benin',
                    'id'=>26
                    ],
                    [
                    'code'=>'BM',
                    'en'=>'Bermuda',
                    'de'=>'Bermuda',
                    'id'=>27
                    ],
                    [
                    'code'=>'BN',
                    'en'=>'Brunei',
                    'de'=>'Brunei Darussalam',
                    'id'=>28
                    ],
                    [
                    'code'=>'BO',
                    'en'=>'Bolivia',
                    'de'=>'Bolivien',
                    'id'=>29
                    ],
                    [
                    'code'=>'BR',
                    'en'=>'Brazil',
                    'de'=>'Brasilien',
                    'id'=>30
                    ],
                    [
                    'code'=>'BS',
                    'en'=>'Bahamas',
                    'de'=>'Bahamas',
                    'id'=>31
                    ],
                    [
                    'code'=>'BT',
                    'en'=>'Bhutan',
                    'de'=>'Bhutan',
                    'id'=>32
                    ],
                    [
                    'code'=>'BV',
                    'en'=>'Bouvet Island',
                    'de'=>'Bouvetinsel',
                    'id'=>33
                    ],
                    [
                    'code'=>'BW',
                    'en'=>'Botswana',
                    'de'=>'Botswana',
                    'id'=>34
                    ],
                    [
                    'code'=>'BY',
                    'en'=>'Belarus',
                    'de'=>'Belarus (Weißrussland)',
                    'id'=>35
                    ],
                    [
                    'code'=>'BZ',
                    'en'=>'Belize',
                    'de'=>'Belize',
                    'id'=>36
                    ],
                    [
                    'code'=>'CA',
                    'en'=>'Canada',
                    'de'=>'Kanada',
                    'id'=>37
                    ],
                    [
                    'code'=>'CC',
                    'en'=>'Cocos (Keeling) Islands',
                    'de'=>'Kokosinseln (Keelinginseln)',
                    'id'=>38
                    ],
                    [
                    'code'=>'CD',
                    'en'=>'Congo (Kinshasa)',
                    'de'=>'Kongo',
                    'id'=>39
                    ],
                    [
                    'code'=>'CF',
                    'en'=>'Central African Republic',
                    'de'=>'Zentralafrikanische Republik',
                    'id'=>40
                    ],
                    [
                    'code'=>'CG',
                    'en'=>'Congo (Brazzaville)',
                    'de'=>'Republik Kongo',
                    'id'=>41
                    ],
                    [
                    'code'=>'CH',
                    'en'=>'Switzerland',
                    'de'=>'Schweiz',
                    'id'=>42
                    ],
                    [
                    'code'=>'CI',
                    'en'=>'Ivory Coast',
                    'de'=>'Elfenbeinküste',
                    'id'=>43
                    ],
                    [
                    'code'=>'CK',
                    'en'=>'Cook Islands',
                    'de'=>'Cookinseln',
                    'id'=>44
                    ],
                    [
                    'code'=>'CL',
                    'en'=>'Chile',
                    'de'=>'Chile',
                    'id'=>45
                    ],
                    [
                    'code'=>'CM',
                    'en'=>'Cameroon',
                    'de'=>'Kamerun',
                    'id'=>46
                    ],
                    [
                    'code'=>'CN',
                    'en'=>'China',
                    'de'=>'China, Volksrepublik',
                    'id'=>47
                    ],
                    [
                    'code'=>'CO',
                    'en'=>'Colombia',
                    'de'=>'Kolumbien',
                    'id'=>48
                    ],
                    [
                    'code'=>'CR',
                    'en'=>'Costa Rica',
                    'de'=>'Costa Rica',
                    'id'=>49
                    ],
                    [
                    'code'=>'CS',
                    'en'=>'Serbia And Montenegro',
                    'de'=>'Serbien und Montenegro',
                    'id'=>50
                    ],
                    [
                    'code'=>'CU',
                    'en'=>'Cuba',
                    'de'=>'Kuba',
                    'id'=>51
                    ],
                    [
                    'code'=>'CV',
                    'en'=>'Cape Verde',
                    'de'=>'Kap Verde',
                    'id'=>52
                    ],
                    [
                    'code'=>'CX',
                    'en'=>'Christmas Island',
                    'de'=>'Weihnachtsinsel',
                    'id'=>53
                    ],
                    [
                    'code'=>'CY',
                    'en'=>'Cyprus',
                    'de'=>'Zypern',
                    'id'=>54
                    ],
                    [
                    'code'=>'CZ',
                    'en'=>'Czech Republic',
                    'de'=>'Tschechische Republik',
                    'id'=>55
                    ],
                    [
                    'code'=>'DE',
                    'en'=>'Germany',
                    'de'=>'Deutschland',
                    'id'=>56
                    ],
                    [
                    'code'=>'DJ',
                    'en'=>'Djibouti',
                    'de'=>'Dschibuti',
                    'id'=>57
                    ],
                    [
                    'code'=>'DK',
                    'en'=>'Denmark',
                    'de'=>'Dänemark',
                    'id'=>58
                    ],
                    [
                    'code'=>'DM',
                    'en'=>'Dominica',
                    'de'=>'Dominica',
                    'id'=>59
                    ],
                    [
                    'code'=>'DO',
                    'en'=>'Dominican Republic',
                    'de'=>'Dominikanische Republik',
                    'id'=>60
                    ],
                    [
                    'code'=>'DZ',
                    'en'=>'Algeria',
                    'de'=>'Algerien',
                    'id'=>61
                    ],
                    [
                    'code'=>'EC',
                    'en'=>'Ecuador',
                    'de'=>'Ecuador',
                    'id'=>62
                    ],
                    [
                    'code'=>'EE',
                    'en'=>'Estonia',
                    'de'=>'Estland (Reval)',
                    'id'=>63
                    ],
                    [
                    'code'=>'EG',
                    'en'=>'Egypt',
                    'de'=>'Ägypten',
                    'id'=>64
                    ],
                    [
                    'code'=>'EH',
                    'en'=>'Western Sahara',
                    'de'=>'Westsahara',
                    'id'=>65
                    ],
                    [
                    'code'=>'ER',
                    'en'=>'Eritrea',
                    'de'=>'Eritrea',
                    'id'=>66
                    ],
                    [
                    'code'=>'ES',
                    'en'=>'Spain',
                    'de'=>'Spanien',
                    'id'=>67
                    ],
                    [
                    'code'=>'ET',
                    'en'=>'Ethiopia',
                    'de'=>'Äthiopien',
                    'id'=>68
                    ],
                    [
                    'code'=>'FI',
                    'en'=>'Finland',
                    'de'=>'Finnland',
                    'id'=>69
                    ],
                    [
                    'code'=>'FJ',
                    'en'=>'Fiji',
                    'de'=>'Fidschi',
                    'id'=>70
                    ],
                    [
                    'code'=>'FK',
                    'en'=>'Falkland Islands',
                    'de'=>'Falklandinseln (Malwinen)',
                    'id'=>71
                    ],
                    [
                    'code'=>'FM',
                    'en'=>'Micronesia',
                    'de'=>'Mikronesien',
                    'id'=>72
                    ],
                    [
                    'code'=>'FO',
                    'en'=>'Faroe Islands',
                    'de'=>'Färöer',
                    'id'=>73
                    ],
                    [
                    'code'=>'FR',
                    'en'=>'France',
                    'de'=>'Frankreich',
                    'id'=>74
                    ],
                    [
                    'code'=>'GA',
                    'en'=>'Gabon',
                    'de'=>'Gabun',
                    'id'=>75
                    ],
                    [
                    'code'=>'GB',
                    'en'=>'United Kingdom',
                    'de'=>'Großbritannien und Nordirland',
                    'id'=>76
                    ],
                    [
                    'code'=>'GD',
                    'en'=>'Grenada',
                    'de'=>'Grenada',
                    'id'=>77
                    ],
                    [
                    'code'=>'GE',
                    'en'=>'Georgia',
                    'de'=>'Georgien',
                    'id'=>78
                    ],
                    [
                    'code'=>'GF',
                    'en'=>'French Guiana',
                    'de'=>'Französisch-Guayana',
                    'id'=>79
                    ],
                    [
                    'code'=>'GG',
                    'en'=>'Guernsey',
                    'de'=>'Guernsey (Kanalinsel)',
                    'id'=>80
                    ],
                    [
                    'code'=>'GH',
                    'en'=>'Ghana',
                    'de'=>'Ghana',
                    'id'=>81
                    ],
                    [
                    'code'=>'GI',
                    'en'=>'Gibraltar',
                    'de'=>'Gibraltar',
                    'id'=>82
                    ],
                    [
                    'code'=>'GL',
                    'en'=>'Greenland',
                    'de'=>'Grönland',
                    'id'=>83
                    ],
                    [
                    'code'=>'GM',
                    'en'=>'Gambia',
                    'de'=>'Gambia',
                    'id'=>84
                    ],
                    [
                    'code'=>'GN',
                    'en'=>'Guinea',
                    'de'=>'Guinea',
                    'id'=>85
                    ],
                    [
                    'code'=>'GP',
                    'en'=>'Guadeloupe',
                    'de'=>'Guadeloupe',
                    'id'=>86
                    ],
                    [
                    'code'=>'GQ',
                    'en'=>'Equatorial Guinea',
                    'de'=>'Äquatorialguinea',
                    'id'=>87
                    ],
                    [
                    'code'=>'GR',
                    'en'=>'Greece',
                    'de'=>'Griechenland',
                    'id'=>88
                    ],
                    [
                    'code'=>'GS',
                    'en'=>'South Georgia and the South Sandwich Islands',
                    'de'=>'Südgeorgien und die Südl. Sandwichinseln',
                    'id'=>89
                    ],
                    [
                    'code'=>'GT',
                    'en'=>'Guatemala',
                    'de'=>'Guatemala',
                    'id'=>90
                    ],
                    [
                    'code'=>'GU',
                    'en'=>'Guam',
                    'de'=>'Guam',
                    'id'=>91
                    ],
                    [
                    'code'=>'GW',
                    'en'=>'Guinea-Bissau',
                    'de'=>'Guinea-Bissau',
                    'id'=>92
                    ],
                    [
                    'code'=>'GY',
                    'en'=>'Guyana',
                    'de'=>'Guyana',
                    'id'=>93
                    ],
                    [
                    'code'=>'HK',
                    'en'=>'Hong Kong S.A.R., China',
                    'de'=>'Hongkong',
                    'id'=>94
                    ],
                    [
                    'code'=>'HM',
                    'en'=>'Heard Island and McDonald Islands',
                    'de'=>'Heard- und McDonald-Inseln',
                    'id'=>95
                    ],
                    [
                    'code'=>'HN',
                    'en'=>'Honduras',
                    'de'=>'Honduras',
                    'id'=>96
                    ],
                    [
                    'code'=>'HR',
                    'en'=>'Croatia',
                    'de'=>'Kroatien',
                    'id'=>97
                    ],
                    [
                    'code'=>'HT',
                    'en'=>'Haiti',
                    'de'=>'Haiti',
                    'id'=>98
                    ],
                    [
                    'code'=>'HU',
                    'en'=>'Hungary',
                    'de'=>'Ungarn',
                    'id'=>99
                    ],
                    [
                    'code'=>'ID',
                    'en'=>'Indonesia',
                    'de'=>'Indonesien',
                    'id'=>100
                    ],
                    [
                    'code'=>'IE',
                    'en'=>'Ireland',
                    'de'=>'Irland',
                    'id'=>101
                    ],
                    [
                    'code'=>'IL',
                    'en'=>'Israel',
                    'de'=>'Israel',
                    'id'=>102
                    ],
                    [
                    'code'=>'IM',
                    'en'=>'Isle of Man',
                    'de'=>'Insel Man',
                    'id'=>103
                    ],
                    [
                    'code'=>'IN',
                    'en'=>'India',
                    'de'=>'Indien',
                    'id'=>104
                    ],
                    [
                    'code'=>'IO',
                    'en'=>'British Indian Ocean Territory',
                    'de'=>'Britisches Territorium im Indischen Ozean',
                    'id'=>105
                    ],
                    [
                    'code'=>'IQ',
                    'en'=>'Iraq',
                    'de'=>'Irak',
                    'id'=>106
                    ],
                    [
                    'code'=>'IR',
                    'en'=>'Iran',
                    'de'=>'Iran',
                    'id'=>107
                    ],
                    [
                    'code'=>'IS',
                    'en'=>'Iceland',
                    'de'=>'Island',
                    'id'=>108
                    ],
                    [
                    'code'=>'IT',
                    'en'=>'Italy',
                    'de'=>'Italien',
                    'id'=>109
                    ],
                    [
                    'code'=>'JE',
                    'en'=>'Jersey',
                    'de'=>'Jersey (Kanalinsel)',
                    'id'=>110
                    ],
                    [
                    'code'=>'JM',
                    'en'=>'Jamaica',
                    'de'=>'Jamaika',
                    'id'=>111
                    ],
                    [
                    'code'=>'JO',
                    'en'=>'Jordan',
                    'de'=>'Jordanien',
                    'id'=>112
                    ],
                    [
                    'code'=>'JP',
                    'en'=>'Japan',
                    'de'=>'Japan',
                    'id'=>113
                    ],
                    [
                    'code'=>'KE',
                    'en'=>'Kenya',
                    'de'=>'Kenia',
                    'id'=>114
                    ],
                    [
                    'code'=>'KG',
                    'en'=>'Kyrgyzstan',
                    'de'=>'Kirgisistan',
                    'id'=>115
                    ],
                    [
                    'code'=>'KH',
                    'en'=>'Cambodia',
                    'de'=>'Kambodscha',
                    'id'=>116
                    ],
                    [
                    'code'=>'KI',
                    'en'=>'Kiribati',
                    'de'=>'Kiribati',
                    'id'=>117
                    ],
                    [
                    'code'=>'KM',
                    'en'=>'Comoros',
                    'de'=>'Komoren',
                    'id'=>118
                    ],
                    [
                    'code'=>'KN',
                    'en'=>'Saint Kitts and Nevis',
                    'de'=>'St. Kitts und Nevis',
                    'id'=>119
                    ],
                    [
                    'code'=>'KP',
                    'en'=>'North Korea',
                    'de'=>'Nordkorea',
                    'id'=>120
                    ],
                    [
                    'code'=>'KR',
                    'en'=>'South Korea',
                    'de'=>'Südkorea',
                    'id'=>121
                    ],
                    [
                    'code'=>'KW',
                    'en'=>'Kuwait',
                    'de'=>'Kuwait',
                    'id'=>122
                    ],
                    [
                    'code'=>'KY',
                    'en'=>'Cayman Islands',
                    'de'=>'Kaimaninseln',
                    'id'=>123
                    ],
                    [
                    'code'=>'KZ',
                    'en'=>'Kazakhstan',
                    'de'=>'Kasachstan',
                    'id'=>124
                    ],
                    [
                    'code'=>'LA',
                    'en'=>'Laos',
                    'de'=>'Laos',
                    'id'=>125
                    ],
                    [
                    'code'=>'LB',
                    'en'=>'Lebanon',
                    'de'=>'Libanon',
                    'id'=>126
                    ],
                    [
                    'code'=>'LC',
                    'en'=>'Saint Lucia',
                    'de'=>'St. Lucia',
                    'id'=>127
                    ],
                    [
                    'code'=>'LI',
                    'en'=>'Liechtenstein',
                    'de'=>'Liechtenstein',
                    'id'=>128
                    ],
                    [
                    'code'=>'LK',
                    'en'=>'Sri Lanka',
                    'de'=>'Sri Lanka',
                    'id'=>129
                    ],
                    [
                    'code'=>'LR',
                    'en'=>'Liberia',
                    'de'=>'Liberia',
                    'id'=>130
                    ],
                    [
                    'code'=>'LS',
                    'en'=>'Lesotho',
                    'de'=>'Lesotho',
                    'id'=>131
                    ],
                    [
                    'code'=>'LT',
                    'en'=>'Lithuania',
                    'de'=>'Litauen',
                    'id'=>132
                    ],
                    [
                    'code'=>'LU',
                    'en'=>'Luxembourg',
                    'de'=>'Luxemburg',
                    'id'=>133
                    ],
                    [
                    'code'=>'LV',
                    'en'=>'Latvia',
                    'de'=>'Lettland',
                    'id'=>134
                    ],
                    [
                    'code'=>'LY',
                    'en'=>'Libya',
                    'de'=>'Libyen',
                    'id'=>135
                    ],
                    [
                    'code'=>'MA',
                    'en'=>'Morocco',
                    'de'=>'Marokko',
                    'id'=>136
                    ],
                    [
                    'code'=>'MC',
                    'en'=>'Monaco',
                    'de'=>'Monaco',
                    'id'=>137
                    ],
                    [
                    'code'=>'MD',
                    'en'=>'Moldova',
                    'de'=>'Moldawien',
                    'id'=>138
                    ],
                    [
                    'code'=>'MG',
                    'en'=>'Madagascar',
                    'de'=>'Madagaskar',
                    'id'=>139
                    ],
                    [
                    'code'=>'MH',
                    'en'=>'Marshall Islands',
                    'de'=>'Marshallinseln',
                    'id'=>140
                    ],
                    [
                    'code'=>'MK',
                    'en'=>'Macedonia',
                    'de'=>'Mazedonien',
                    'id'=>141
                    ],
                    [
                    'code'=>'ML',
                    'en'=>'Mali',
                    'de'=>'Mali',
                    'id'=>142
                    ],
                    [
                    'code'=>'MM',
                    'en'=>'Myanmar',
                    'de'=>'Myanmar (Burma)',
                    'id'=>143
                    ],
                    [
                    'code'=>'MN',
                    'en'=>'Mongolia',
                    'de'=>'Mongolei',
                    'id'=>144
                    ],
                    [
                    'code'=>'MO',
                    'en'=>'Macao S.A.R., China',
                    'de'=>'Macao',
                    'id'=>145
                    ],
                    [
                    'code'=>'MP',
                    'en'=>'Northern Mariana Islands',
                    'de'=>'Nördliche Marianen',
                    'id'=>146
                    ],
                    [
                    'code'=>'MQ',
                    'en'=>'Martinique',
                    'de'=>'Martinique',
                    'id'=>147
                    ],
                    [
                    'code'=>'MR',
                    'en'=>'Mauritania',
                    'de'=>'Mauretanien',
                    'id'=>148
                    ],
                    [
                    'code'=>'MS',
                    'en'=>'Montserrat',
                    'de'=>'Montserrat',
                    'id'=>149
                    ],
                    [
                    'code'=>'MT',
                    'en'=>'Malta',
                    'de'=>'Malta',
                    'id'=>150
                    ],
                    [
                    'code'=>'MU',
                    'en'=>'Mauritius',
                    'de'=>'Mauritius',
                    'id'=>151
                    ],
                    [
                    'code'=>'MV',
                    'en'=>'Maldives',
                    'de'=>'Malediven',
                    'id'=>152
                    ],
                    [
                    'code'=>'MW',
                    'en'=>'Malawi',
                    'de'=>'Malawi',
                    'id'=>153
                    ],
                    [
                    'code'=>'MX',
                    'en'=>'Mexico',
                    'de'=>'Mexiko',
                    'id'=>154
                    ],
                    [
                    'code'=>'MY',
                    'en'=>'Malaysia',
                    'de'=>'Malaysia',
                    'id'=>155
                    ],
                    [
                    'code'=>'MZ',
                    'en'=>'Mozambique',
                    'de'=>'Mosambik',
                    'id'=>156
                    ],
                    [
                    'code'=>'NA',
                    'en'=>'Namibia',
                    'de'=>'Namibia',
                    'id'=>157
                    ],
                    [
                    'code'=>'NC',
                    'en'=>'New Caledonia',
                    'de'=>'Neukaledonien',
                    'id'=>158
                    ],
                    [
                    'code'=>'NE',
                    'en'=>'Niger',
                    'de'=>'Niger',
                    'id'=>159
                    ],
                    [
                    'code'=>'NF',
                    'en'=>'Norfolk Island',
                    'de'=>'Norfolkinsel',
                    'id'=>160
                    ],
                    [
                    'code'=>'NG',
                    'en'=>'Nigeria',
                    'de'=>'Nigeria',
                    'id'=>161
                    ],
                    [
                    'code'=>'NI',
                    'en'=>'Nicaragua',
                    'de'=>'Nicaragua',
                    'id'=>162
                    ],
                    [
                    'code'=>'NL',
                    'en'=>'Netherlands',
                    'de'=>'Niederlande',
                    'id'=>163
                    ],
                    [
                    'code'=>'NO',
                    'en'=>'Norway',
                    'de'=>'Norwegen',
                    'id'=>164
                    ],
                    [
                    'code'=>'NP',
                    'en'=>'Nepal',
                    'de'=>'Nepal',
                    'id'=>165
                    ],
                    [
                    'code'=>'NR',
                    'en'=>'Nauru',
                    'de'=>'Nauru',
                    'id'=>166
                    ],
                    [
                    'code'=>'NU',
                    'en'=>'Niue',
                    'de'=>'Niue',
                    'id'=>167
                    ],
                    [
                    'code'=>'NZ',
                    'en'=>'New Zealand',
                    'de'=>'Neuseeland',
                    'id'=>168
                    ],
                    [
                    'code'=>'OM',
                    'en'=>'Oman',
                    'de'=>'Oman',
                    'id'=>169
                    ],
                    [
                    'code'=>'PA',
                    'en'=>'Panama',
                    'de'=>'Panama',
                    'id'=>170
                    ],
                    [
                    'code'=>'PE',
                    'en'=>'Peru',
                    'de'=>'Peru',
                    'id'=>171
                    ],
                    [
                    'code'=>'PF',
                    'en'=>'French Polynesia',
                    'de'=>'Französisch-Polynesien',
                    'id'=>172
                    ],
                    [
                    'code'=>'PG',
                    'en'=>'Papua New Guinea',
                    'de'=>'Papua-Neuguinea',
                    'id'=>173
                    ],
                    [
                    'code'=>'PH',
                    'en'=>'Philippines',
                    'de'=>'Philippinen',
                    'id'=>174
                    ],
                    [
                    'code'=>'PK',
                    'en'=>'Pakistan',
                    'de'=>'Pakistan',
                    'id'=>175
                    ],
                    [
                    'code'=>'PL',
                    'en'=>'Poland',
                    'de'=>'Polen',
                    'id'=>176
                    ],
                    [
                    'code'=>'PM',
                    'en'=>'Saint Pierre and Miquelon',
                    'de'=>'St. Pierre und Miquelon',
                    'id'=>177
                    ],
                    [
                    'code'=>'PN',
                    'en'=>'Pitcairn',
                    'de'=>'Pitcairninseln',
                    'id'=>178
                    ],
                    [
                    'code'=>'PR',
                    'en'=>'Puerto Rico',
                    'de'=>'Puerto Rico',
                    'id'=>179
                    ],
                    [
                    'code'=>'PS',
                    'en'=>'Palestinian Territory',
                    'de'=>'Palästinensische Autonomiegebiete',
                    'id'=>180
                    ],
                    [
                    'code'=>'PT',
                    'en'=>'Portugal',
                    'de'=>'Portugal',
                    'id'=>181
                    ],
                    [
                    'code'=>'PW',
                    'en'=>'Palau',
                    'de'=>'Palau',
                    'id'=>182
                    ],
                    [
                    'code'=>'PY',
                    'en'=>'Paraguay',
                    'de'=>'Paraguay',
                    'id'=>183
                    ],
                    [
                    'code'=>'QA',
                    'en'=>'Qatar',
                    'de'=>'Katar',
                    'id'=>184
                    ],
                    [
                    'code'=>'RE',
                    'en'=>'Reunion',
                    'de'=>'Reunion',
                    'id'=>185
                    ],
                    [
                    'code'=>'RO',
                    'en'=>'Romania',
                    'de'=>'Rumänien',
                    'id'=>186
                    ],
                    [
                    'code'=>'RU',
                    'en'=>'Russia',
                    'de'=>'Russische Föderation',
                    'id'=>187
                    ],
                    [
                    'code'=>'RW',
                    'en'=>'Rwanda',
                    'de'=>'Ruanda',
                    'id'=>188
                    ],
                    [
                    'code'=>'SA',
                    'en'=>'Saudi Arabia',
                    'de'=>'Saudi-Arabien',
                    'id'=>189
                    ],
                    [
                    'code'=>'SB',
                    'en'=>'Solomon Islands',
                    'de'=>'Salomonen',
                    'id'=>190
                    ],
                    [
                    'code'=>'SC',
                    'en'=>'Seychelles',
                    'de'=>'Seychellen',
                    'id'=>191
                    ],
                    [
                    'code'=>'SD',
                    'en'=>'Sudan',
                    'de'=>'Sudan',
                    'id'=>192
                    ],
                    [
                    'code'=>'SE',
                    'en'=>'Sweden',
                    'de'=>'Schweden',
                    'id'=>193
                    ],
                    [
                    'code'=>'SG',
                    'en'=>'Singapore',
                    'de'=>'Singapur',
                    'id'=>194
                    ],
                    [
                    'code'=>'SH',
                    'en'=>'Saint Helena',
                    'de'=>'St. Helena',
                    'id'=>195
                    ],
                    [
                    'code'=>'SI',
                    'en'=>'Slovenia',
                    'de'=>'Slowenien',
                    'id'=>196
                    ],
                    [
                    'code'=>'SJ',
                    'en'=>'Svalbard and Jan Mayen',
                    'de'=>'Svalbard und Jan Mayen',
                    'id'=>197
                    ],
                    [
                    'code'=>'SK',
                    'en'=>'Slovakia',
                    'de'=>'Slowakei',
                    'id'=>198
                    ],
                    [
                    'code'=>'SL',
                    'en'=>'Sierra Leone',
                    'de'=>'Sierra Leone',
                    'id'=>199
                    ],
                    [
                    'code'=>'SM',
                    'en'=>'San Marino',
                    'de'=>'San Marino',
                    'id'=>200
                    ],
                    [
                    'code'=>'SN',
                    'en'=>'Senegal',
                    'de'=>'Senegal',
                    'id'=>201
                    ],
                    [
                    'code'=>'SO',
                    'en'=>'Somalia',
                    'de'=>'Somalia',
                    'id'=>202
                    ],
                    [
                    'code'=>'SR',
                    'en'=>'Suriname',
                    'de'=>'Suriname',
                    'id'=>203
                    ],
                    [
                    'code'=>'ST',
                    'en'=>'Sao Tome and Principe',
                    'de'=>'Sao Tome und PrÃincipe',
                    'id'=>204
                    ],
                    [
                    'code'=>'SV',
                    'en'=>'El Salvador',
                    'de'=>'El Salvador',
                    'id'=>205
                    ],
                    [
                    'code'=>'SY',
                    'en'=>'Syria',
                    'de'=>'Syrien',
                    'id'=>206
                    ],
                    [
                    'code'=>'SZ',
                    'en'=>'Swaziland',
                    'de'=>'Swasiland',
                    'id'=>207
                    ],
                    [
                    'code'=>'TC',
                    'en'=>'Turks and Caicos Islands',
                    'de'=>'Turks- und Caicosinseln',
                    'id'=>208
                    ],
                    [
                    'code'=>'TD',
                    'en'=>'Chad',
                    'de'=>'Tschad',
                    'id'=>209
                    ],
                    [
                    'code'=>'TF',
                    'en'=>'French Southern Territories',
                    'de'=>'Französische Süd- und Antarktisgebiete',
                    'id'=>210
                    ],
                    [
                    'code'=>'TG',
                    'en'=>'Togo',
                    'de'=>'Togo',
                    'id'=>211
                    ],
                    [
                    'code'=>'TH',
                    'en'=>'Thailand',
                    'de'=>'Thailand',
                    'id'=>212
                    ],
                    [
                    'code'=>'TJ',
                    'en'=>'Tajikistan',
                    'de'=>'Tadschikistan',
                    'id'=>213
                    ],
                    [
                    'code'=>'TK',
                    'en'=>'Tokelau',
                    'de'=>'Tokelau',
                    'id'=>214
                    ],
                    [
                    'code'=>'TL',
                    'en'=>'East Timor',
                    'de'=>'Timor-Leste',
                    'id'=>215
                    ],
                    [
                    'code'=>'TM',
                    'en'=>'Turkmenistan',
                    'de'=>'Turkmenistan',
                    'id'=>216
                    ],
                    [
                    'code'=>'TN',
                    'en'=>'Tunisia',
                    'de'=>'Tunesien',
                    'id'=>217
                    ],
                    [
                    'code'=>'TO',
                    'en'=>'Tonga',
                    'de'=>'Tonga',
                    'id'=>218
                    ],
                    [
                    'code'=>'TR',
                    'en'=>'Turkey',
                    'de'=>'Türkei',
                    'id'=>219
                    ],
                    [
                    'code'=>'TT',
                    'en'=>'Trinidad and Tobago',
                    'de'=>'Trinidad und Tobago',
                    'id'=>220
                    ],
                    [
                    'code'=>'TV',
                    'en'=>'Tuvalu',
                    'de'=>'Tuvalu',
                    'id'=>221
                    ],
                    [
                    'code'=>'TW',
                    'en'=>'Taiwan',
                    'de'=>'Taiwan',
                    'id'=>222
                    ],
                    [
                    'code'=>'TZ',
                    'en'=>'Tanzania',
                    'de'=>'Tansania',
                    'id'=>223
                    ],
                    [
                    'code'=>'UA',
                    'en'=>'Ukraine',
                    'de'=>'Ukraine',
                    'id'=>224
                    ],
                    [
                    'code'=>'UG',
                    'en'=>'Uganda',
                    'de'=>'Uganda',
                    'id'=>225
                    ],
                    [
                    'code'=>'UM',
                    'en'=>'United States Minor Outlying Islands',
                    'de'=>'Amerikanisch-Ozeanien',
                    'id'=>226
                    ],
                    [
                    'code'=>'US',
                    'en'=>'United States',
                    'de'=>'Vereinigte Staaten von Amerika',
                    'id'=>227
                    ],
                    [
                    'code'=>'UY',
                    'en'=>'Uruguay',
                    'de'=>'Uruguay',
                    'id'=>228
                    ],
                    [
                    'code'=>'UZ',
                    'en'=>'Uzbekistan',
                    'de'=>'Usbekistan',
                    'id'=>229
                    ],
                    [
                    'code'=>'VA',
                    'en'=>'Vatican',
                    'de'=>'Vatikanstadt',
                    'id'=>230
                    ],
                    [
                    'code'=>'VC',
                    'en'=>'Saint Vincent and the Grenadines',
                    'de'=>'St. Vincent und die Grenadinen',
                    'id'=>231
                    ],
                    [
                    'code'=>'VE',
                    'en'=>'Venezuela',
                    'de'=>'Venezuela',
                    'id'=>232
                    ],
                    [
                    'code'=>'VG',
                    'en'=>'British Virgin Islands',
                    'de'=>'Britische Jungferninseln',
                    'id'=>233
                    ],
                    [
                    'code'=>'VI',
                    'en'=>'U.S. Virgin Islands',
                    'de'=>'Amerikanische Jungferninseln',
                    'id'=>234
                    ],
                    [
                    'code'=>'VN',
                    'en'=>'Vietnam',
                    'de'=>'Vietnam',
                    'id'=>235
                    ],
                    [
                    'code'=>'VU',
                    'en'=>'Vanuatu',
                    'de'=>'Vanuatu',
                    'id'=>236
                    ],
                    [
                    'code'=>'WF',
                    'en'=>'Wallis and Futuna',
                    'de'=>'Wallis und Futuna',
                    'id'=>237
                    ],
                    [
                    'code'=>'WS',
                    'en'=>'Samoa',
                    'de'=>'Samoa',
                    'id'=>238
                    ],
                    [
                    'code'=>'YE',
                    'en'=>'Yemen',
                    'de'=>'Jemen',
                    'id'=>239
                    ],
                    [
                    'code'=>'YT',
                    'en'=>'Mayotte',
                    'de'=>'Mayotte',
                    'id'=>240
                    ],
                    [
                    'code'=>'ZA',
                    'en'=>'South Africa',
                    'de'=>'Südafrika',
                    'id'=>241
                    ],
                    [
                    'code'=>'ZM',
                    'en'=>'Zambia',
                    'de'=>'Sambia',
                    'id'=>242
                    ],
                    [
                    'code'=>'ZW',
                    'en'=>'Zimbabwe',
                    'de'=>'Simbabwe',
                    'id'=>243
                    ]
            ];

        Country::insert($countries);
    }
}
