<?php

use App\State;
use Illuminate\Database\Seeder;

class StatesTableSeeder extends Seeder
{
    public function run()
    {
        $states = [[
                    'id'=>2,
                    'state'=>'Bayern',
                    'country_code'=>'DE', 
                    ],
                    [
                    'id'=>3,
                    'state'=>'Berlin',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>4,
                    'state'=>'Brandenburg',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>5,
                    'state'=>'Bremen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>6,
                    'state'=>'Hamburg',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>7,
                    'state'=>'Hessen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>8,
                    'state'=>'Mecklenburg-Vorpommern',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>9,
                    'state'=>'Niedersachsen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>10,
                    'state'=>'Nordrhein-Westfalen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>11,
                    'state'=>'Rheinland-Pfalz',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>12,
                    'state'=>'Saarland',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>13,
                    'state'=>'Sachsen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>14,
                    'state'=>'Sachsen-Anhalt',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>15,
                    'state'=>'Schleswig-Holstein',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>17,
                    'state'=>'Thueringen',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>18,
                    'state'=>'Baden-Wuerttemberg',
                    'country_code'=>'DE',
                    ],
                    [
                    'id'=>19,
                    'state'=>'Burgenland',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>20,
                    'state'=>'Kärnten',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>21,
                    'state'=>'Niederösterreich',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>22,
                    'state'=>'Oberösterreich',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>23,
                    'state'=>'Salzburg',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>24,
                    'state'=>'Steiermark',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>25,
                    'state'=>'Tirol',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>26,
                    'state'=>'Voralberg',
                    'country_code'=>'AT',
                    ],
                    [
                    'id'=>27,
                    'state'=>'Wien',
                    'country_code'=>'AT',
                    ]
            ];

        State::insert($states);
    }
}
