import './login_view.cy.js'
import './login_view_authenticate_admin.cy.js'
import './login_view_authenticate_creator.cy.js'
import './login_view_authenticate_indexer.cy.js'
import './login_view_authenticate_schooladmin.cy.js'
import './login_view_authenticate_teacher.cy.js'
import './login_view_authenticate_student.cy.js'
import './login_view_authenticate_parent.cy.js'
import './login_view_authenticate_guest.cy.js'

