FROM php:7.4-apache

RUN apt-get update --fix-missing -q

# 1. development packages
RUN apt-get install -y \
    git \
    zip \
    curl \
    sudo \
    unzip \
    libicu-dev \
    libbz2-dev \
    libpng-dev \
    libmcrypt-dev \
    libreadline-dev \
    libfreetype6-dev \
    libzip-dev \
    libonig-dev \
    g++ \
    libwebp-dev \
    libjpeg62-turbo-dev \
    nano \
    libgmp-dev \
    libldap2-dev

RUN docker-php-ext-configure gd --with-jpeg=/usr/include/ --with-freetype=/usr/include/ && \
    docker-php-ext-install bz2 intl opcache calendar gd pdo pdo_mysql zip gmp bcmath pcntl ldap sysvmsg exif \
    && a2enmod rewrite

# 2. apache configs + document root
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# 3. mod_rewrite for URL rewrite and mod_headers for .htaccess extra headers like Access-Control-Allow-Origin-
RUN a2enmod rewrite && service apache2 restart

# 4. start with base php config, then add extensions
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# 5. composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 6. we need a user with the same UID/GID with host user
# so when we execute CLI commands, all the host file's ownership remains intact
# otherwise command from inside container will create root-owned files and directories
ARG uid
ARG username
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN useradd -G www-data,root -u $uid -d /home/$username $username
RUN mkdir -p /home/$username/.composer && \
    chown -R www-data:$username /home/$username

EXPOSE 80

COPY . /var/www/html/

CMD ["/usr/sbin/apache2", "-DFOREGROUND"]
